// ── School Database — 750+ real colleges (U.S. & Canada) ───────────────────
// Raw fixed data only. "type" (reach/match/safety) is calculated per student.

export interface SchoolRecord {
  name: string;
  url: string;
  state: string;
  region: string;
  campusSize: string;
  enrollment: number;
  admitRate: number;
  testPolicy: string;
  ncaaDivision: string;
}

const STATE_TO_REGION: Record<string, string> = {
  MA: "Northeast", CT: "Northeast", NY: "Northeast", RI: "Northeast",
  ME: "Northeast", VT: "Northeast", NH: "Northeast",
  VA: "Mid-Atlantic", DC: "Mid-Atlantic", MD: "Mid-Atlantic", PA: "Mid-Atlantic",
  DE: "Mid-Atlantic", NJ: "Mid-Atlantic", WV: "Mid-Atlantic",
  TX: "South", GA: "South", NC: "South", FL: "South", TN: "South",
  SC: "South", AL: "South", LA: "South", AR: "South", MS: "South", KY: "South", OK: "South",
  IL: "Midwest", MI: "Midwest", OH: "Midwest", WI: "Midwest", MN: "Midwest",
  IN: "Midwest", IA: "Midwest", MO: "Midwest", KS: "Midwest", NE: "Midwest",
  ND: "Midwest", SD: "Midwest",
  CA: "West", OR: "West", WA: "West", CO: "West", AZ: "West", UT: "West",
  NV: "West", NM: "West", MT: "West", WY: "West", ID: "West", HI: "West", AK: "West",
  // Canadian provinces
  ON: "Canada", BC: "Canada", AB: "Canada", QC: "Canada",
  MB: "Canada", SK: "Canada", NS: "Canada", NB: "Canada",
  NL: "Canada", PE: "Canada",
};

function getRegion(state: string): string {
  return STATE_TO_REGION[state] || "Other";
}

function getCampusSize(enrollment: number): string {
  if (enrollment < 2000) return "Micro";
  if (enrollment < 5000) return "Small";
  if (enrollment < 15000) return "Medium";
  if (enrollment < 30000) return "Large";
  return "Mega";
}

// Compact raw format: [name, url, state, enrollment, admitRate, testPolicy]
type R = [string, string, string, number, number, string];

const RAW: R[] = [
  // ═══════════════════════════════════════════════════════════════════════════
  // MICRO (<2,000 undergrads)
  // ═══════════════════════════════════════════════════════════════════════════

  // Northeast — Micro
  ["Amherst College", "amherst.edu", "MA", 1900, 0.09, "Test Optional"],
  ["Bates College", "bates.edu", "ME", 1800, 0.14, "Test Optional"],
  ["Bowdoin College", "bowdoin.edu", "ME", 1900, 0.09, "Test Optional"],
  ["Colby College", "colby.edu", "ME", 1950, 0.07, "Test Optional"],
  ["Hampshire College", "hampshire.edu", "MA", 1300, 0.80, "Test Optional"],
  ["Sarah Lawrence College", "sarahlawrence.edu", "NY", 1400, 0.55, "Test Optional"],
  ["Bennington College", "bennington.edu", "VT", 800, 0.58, "Test Optional"],
  ["Wheaton College Massachusetts", "wheatoncollege.edu", "MA", 1800, 0.72, "Test Optional"],
  ["Simon's Rock", "simons-rock.edu", "MA", 400, 0.85, "Test Optional"],

  // Mid-Atlantic — Micro
  ["Swarthmore College", "swarthmore.edu", "PA", 1600, 0.07, "Test Optional"],
  ["Haverford College", "haverford.edu", "PA", 1400, 0.13, "Test Optional"],
  ["Bryn Mawr College", "brynmawr.edu", "PA", 1400, 0.32, "Test Optional"],
  ["Dickinson College", "dickinson.edu", "PA", 1900, 0.39, "Test Optional"],
  ["Gettysburg College", "gettysburg.edu", "PA", 1900, 0.45, "Test Optional"],
  ["Muhlenberg College", "muhlenberg.edu", "PA", 1800, 0.48, "Test Optional"],
  ["Allegheny College", "allegheny.edu", "PA", 1600, 0.74, "Test Optional"],
  ["Ursinus College", "ursinus.edu", "PA", 1200, 0.78, "Test Optional"],
  ["Washington College", "washcoll.edu", "MD", 1100, 0.72, "Test Optional"],
  ["Randolph-Macon College", "rmc.edu", "VA", 1500, 0.80, "Test Optional"],
  ["Roanoke College", "roanoke.edu", "VA", 1800, 0.82, "Test Optional"],
  ["Hampden-Sydney College", "hsc.edu", "VA", 1000, 0.85, "Test Optional"],
  ["Hollins University", "hollins.edu", "VA", 600, 0.88, "Test Optional"],
  ["Sweet Briar College", "sbc.edu", "VA", 400, 0.90, "Test Optional"],
  ["Bridgewater College", "bridgewater.edu", "VA", 1500, 0.85, "Test Optional"],
  ["St. John's College", "sjc.edu", "MD", 450, 0.72, "Test Optional"],
  ["Juniata College", "juniata.edu", "PA", 1300, 0.72, "Test Optional"],
  ["Goucher College", "goucher.edu", "MD", 1100, 0.80, "Test Optional"],
  ["McDaniel College", "mcdaniel.edu", "MD", 1600, 0.78, "Test Optional"],
  ["Lycoming College", "lycoming.edu", "PA", 1100, 0.82, "Test Optional"],

  // South — Micro
  ["Davidson College", "davidson.edu", "NC", 1900, 0.17, "Test Optional"],
  ["Sewanee University of the South", "sewanee.edu", "TN", 1700, 0.55, "Test Optional"],
  ["Wofford College", "wofford.edu", "SC", 1800, 0.58, "Test Optional"],
  ["Centre College", "centre.edu", "KY", 1500, 0.59, "Test Optional"],
  ["Hendrix College", "hendrix.edu", "AR", 1100, 0.65, "Test Optional"],
  ["Eckerd College", "eckerd.edu", "FL", 1800, 0.72, "Test Optional"],
  ["Agnes Scott College", "agnesscott.edu", "GA", 1000, 0.78, "Test Optional"],
  ["Guilford College", "guilford.edu", "NC", 1200, 0.80, "Test Optional"],
  ["Millsaps College", "millsaps.edu", "MS", 800, 0.60, "Test Optional"],
  ["Austin College", "austincollege.edu", "TX", 1300, 0.55, "Test Optional"],
  ["Oglethorpe University", "oglethorpe.edu", "GA", 1400, 0.78, "Test Optional"],
  ["Birmingham-Southern College", "bsc.edu", "AL", 1100, 0.65, "Test Optional"],
  ["Berry College", "berry.edu", "GA", 1900, 0.62, "Test Optional"],
  ["Transylvania University", "transy.edu", "KY", 1000, 0.72, "Test Optional"],
  ["Southwestern University", "southwestern.edu", "TX", 1500, 0.48, "Test Optional"],
  ["Flagler College", "flagler.edu", "FL", 1900, 0.65, "Test Optional"],

  // Midwest — Micro
  ["Carleton College", "carleton.edu", "MN", 1900, 0.16, "Test Optional"],
  ["Grinnell College", "grinnell.edu", "IA", 1700, 0.13, "Test Optional"],
  ["Kenyon College", "kenyon.edu", "OH", 1700, 0.36, "Test Optional"],
  ["Macalester College", "macalester.edu", "MN", 1900, 0.28, "Test Optional"],
  ["Denison University", "denison.edu", "OH", 1900, 0.31, "Test Optional"],
  ["St. Olaf College", "stolaf.edu", "MN", 1800, 0.52, "Test Optional"],
  ["DePauw University", "depauw.edu", "IN", 1800, 0.63, "Test Optional"],
  ["Lake Forest College", "lakeforest.edu", "IL", 1600, 0.62, "Test Optional"],
  ["Kalamazoo College", "kzoo.edu", "MI", 1500, 0.72, "Test Optional"],
  ["Wabash College", "wabash.edu", "IN", 800, 0.72, "Test Optional"],
  ["Knox College", "knox.edu", "IL", 1200, 0.72, "Test Optional"],
  ["Beloit College", "beloit.edu", "WI", 1100, 0.70, "Test Optional"],
  ["Cornell College", "cornellcollege.edu", "IA", 1000, 0.72, "Test Optional"],
  ["Earlham College", "earlham.edu", "IN", 800, 0.65, "Test Optional"],
  ["Ripon College", "ripon.edu", "WI", 700, 0.78, "Test Optional"],
  ["Alma College", "alma.edu", "MI", 1400, 0.72, "Test Optional"],
  ["Albion College", "albion.edu", "MI", 1300, 0.78, "Test Optional"],
  ["Hillsdale College", "hillsdale.edu", "MI", 1500, 0.35, "Test Required"],
  ["Lawrence University", "lawrence.edu", "WI", 1500, 0.62, "Test Optional"],
  ["Oberlin College", "oberlin.edu", "OH", 1900, 0.30, "Test Optional"],
  ["Wooster College", "wooster.edu", "OH", 1900, 0.60, "Test Optional"],

  // West — Micro
  ["Pomona College", "pomona.edu", "CA", 1600, 0.07, "Test Optional"],
  ["Claremont McKenna College", "cmc.edu", "CA", 1400, 0.09, "Test Optional"],
  ["Harvey Mudd College", "hmc.edu", "CA", 900, 0.13, "Test Optional"],
  ["Pitzer College", "pitzer.edu", "CA", 1100, 0.15, "Test Optional"],
  ["Reed College", "reed.edu", "OR", 1500, 0.41, "Test Optional"],
  ["Whitman College", "whitman.edu", "WA", 1500, 0.51, "Test Optional"],
  ["Lewis & Clark College", "lclark.edu", "OR", 1900, 0.78, "Test Optional"],
  ["Willamette University", "willamette.edu", "OR", 1800, 0.82, "Test Optional"],
  ["University of Puget Sound", "pugetsound.edu", "WA", 1900, 0.78, "Test Optional"],
  ["Mills College", "mills.edu", "CA", 800, 0.85, "Test Optional"],
  ["Linfield University", "linfield.edu", "OR", 1500, 0.85, "Test Optional"],
  ["Pacific University", "pacificu.edu", "OR", 1700, 0.80, "Test Optional"],

  // ═══════════════════════════════════════════════════════════════════════════
  // SMALL (2,000–4,999 undergrads)
  // ═══════════════════════════════════════════════════════════════════════════

  // Northeast — Small
  ["Williams College", "williams.edu", "MA", 2100, 0.10, "Test Optional"],
  ["Middlebury College", "middlebury.edu", "VT", 2800, 0.16, "Test Optional"],
  ["Colgate University", "colgate.edu", "NY", 3200, 0.13, "Test Optional"],
  ["Hamilton College", "hamilton.edu", "NY", 2000, 0.12, "Test Optional"],
  ["Barnard College", "barnard.edu", "NY", 2600, 0.09, "Test Optional"],
  ["Wellesley College", "wellesley.edu", "MA", 2400, 0.13, "Test Optional"],
  ["Vassar College", "vassar.edu", "NY", 2500, 0.20, "Test Optional"],
  ["Connecticut College", "conncoll.edu", "CT", 2000, 0.38, "Test Optional"],
  ["Trinity College", "trincoll.edu", "CT", 2200, 0.33, "Test Optional"],
  ["Skidmore College", "skidmore.edu", "NY", 2700, 0.42, "Test Optional"],
  ["St. Lawrence University", "stlawu.edu", "NY", 2400, 0.49, "Test Optional"],
  ["Union College", "union.edu", "NY", 2200, 0.38, "Test Optional"],
  ["Hobart and William Smith", "hws.edu", "NY", 2000, 0.60, "Test Optional"],
  ["Stonehill College", "stonehill.edu", "MA", 2500, 0.72, "Test Optional"],
  ["Ithaca College", "ithaca.edu", "NY", 4500, 0.70, "Test Optional"],
  ["Siena College", "siena.edu", "NY", 3200, 0.75, "Test Optional"],

  // Mid-Atlantic — Small
  ["Bucknell University", "bucknell.edu", "PA", 3800, 0.32, "Test Optional"],
  ["Lafayette College", "lafayette.edu", "PA", 2700, 0.38, "Test Optional"],
  ["Washington and Lee University", "wlu.edu", "VA", 2300, 0.17, "Test Optional"],
  ["University of Richmond", "richmond.edu", "VA", 3500, 0.25, "Test Optional"],
  ["Franklin & Marshall College", "fandm.edu", "PA", 2300, 0.30, "Test Optional"],
  ["Susquehanna University", "susqu.edu", "PA", 2100, 0.72, "Test Optional"],
  ["Elizabethtown College", "etown.edu", "PA", 2000, 0.80, "Test Optional"],
  ["York College of Pennsylvania", "ycp.edu", "PA", 3500, 0.85, "Test Optional"],
  ["Randolph College", "randolphcollege.edu", "VA", 2000, 0.82, "Test Optional"],
  ["Christopher Newport University", "cnu.edu", "VA", 4500, 0.73, "Test Optional"],

  // South — Small
  ["Furman University", "furman.edu", "SC", 2800, 0.62, "Test Optional"],
  ["Rhodes College", "rhodes.edu", "TN", 2000, 0.52, "Test Optional"],
  ["College of Charleston", "cofc.edu", "SC", 4800, 0.75, "Test Optional"],
  ["Rollins College", "rollins.edu", "FL", 3200, 0.55, "Test Optional"],
  ["Trinity University", "trinity.edu", "TX", 2400, 0.38, "Test Optional"],
  ["University of the South", "sewanee.edu", "TN", 2000, 0.55, "Test Optional"],
  ["Stetson University", "stetson.edu", "FL", 3200, 0.68, "Test Optional"],
  ["Samford University", "samford.edu", "AL", 3600, 0.82, "Test Optional"],
  ["Mercer University", "mercer.edu", "GA", 3500, 0.78, "Test Optional"],
  ["Presbyterian College", "presby.edu", "SC", 2000, 0.82, "Test Optional"],
  ["Hanover College", "hanover.edu", "IN", 2000, 0.82, "Test Optional"],

  // Midwest — Small
  ["Colorado College", "coloradocollege.edu", "CO", 2200, 0.13, "Test Optional"],
  ["College of Wooster", "wooster.edu", "OH", 2000, 0.60, "Test Optional"],
  ["Wheaton College Illinois", "wheaton.edu", "IL", 2400, 0.80, "Test Optional"],
  ["Luther College", "luther.edu", "IA", 2000, 0.78, "Test Optional"],
  ["Hope College", "hope.edu", "MI", 3000, 0.78, "Test Optional"],
  ["Wittenberg University", "wittenberg.edu", "OH", 2000, 0.85, "Test Optional"],
  ["Ohio Wesleyan University", "owu.edu", "OH", 2000, 0.72, "Test Optional"],
  ["Augustana College", "augustana.edu", "IL", 2500, 0.62, "Test Optional"],
  ["Gustavus Adolphus College", "gustavus.edu", "MN", 2200, 0.72, "Test Optional"],
  ["College of Saint Benedict", "csbsju.edu", "MN", 3500, 0.78, "Test Optional"],

  // West — Small
  ["Occidental College", "oxy.edu", "CA", 2000, 0.37, "Test Optional"],
  ["Scripps College", "scrippscollege.edu", "CA", 2000, 0.28, "Test Optional"],
  ["Whitworth University", "whitworth.edu", "WA", 2300, 0.80, "Test Optional"],
  ["University of Redlands", "redlands.edu", "CA", 2800, 0.72, "Test Optional"],
  ["Gonzaga University", "gonzaga.edu", "WA", 4900, 0.62, "Test Optional"],
  ["Carroll College", "carroll.edu", "MT", 2000, 0.82, "Test Optional"],
  ["Westmont College", "westmont.edu", "CA", 2000, 0.72, "Test Optional"],
  ["Pacific Lutheran University", "plu.edu", "WA", 2800, 0.80, "Test Optional"],

  // ═══════════════════════════════════════════════════════════════════════════
  // MEDIUM (5,000–14,999 undergrads)
  // ═══════════════════════════════════════════════════════════════════════════

  // Northeast — Medium
  ["Tufts University", "tufts.edu", "MA", 6700, 0.10, "Test Optional"],
  ["Boston College", "bc.edu", "MA", 10000, 0.16, "Test Optional"],
  ["Northeastern University", "northeastern.edu", "MA", 14000, 0.07, "Test Optional"],
  ["Yale University", "yale.edu", "CT", 6500, 0.05, "Test Required"],
  ["Brown University", "brown.edu", "RI", 7200, 0.05, "Test Required"],
  ["Dartmouth College", "dartmouth.edu", "NH", 4500, 0.06, "Test Required"],
  ["MIT", "mit.edu", "MA", 4600, 0.04, "Test Required"],
  ["Providence College", "providence.edu", "RI", 4900, 0.55, "Test Optional"],
  ["Quinnipiac University", "quinnipiac.edu", "CT", 7200, 0.72, "Test Optional"],
  ["Marist College", "marist.edu", "NY", 5500, 0.68, "Test Optional"],
  ["Fairfield University", "fairfield.edu", "CT", 5200, 0.60, "Test Optional"],
  ["College of the Holy Cross", "holycross.edu", "MA", 3100, 0.32, "Test Optional"],
  ["Suffolk University", "suffolk.edu", "MA", 5500, 0.85, "Test Optional"],

  // Mid-Atlantic — Medium
  ["Carnegie Mellon University", "cmu.edu", "PA", 7400, 0.12, "Test Required"],
  ["Villanova University", "villanova.edu", "PA", 7000, 0.23, "Test Optional"],
  ["Lehigh University", "lehigh.edu", "PA", 5600, 0.32, "Test Optional"],
  ["Georgetown University", "georgetown.edu", "DC", 7800, 0.13, "Test Required"],
  ["College of William & Mary", "wm.edu", "VA", 6800, 0.33, "Test Optional"],
  ["American University", "american.edu", "DC", 8500, 0.44, "Test Optional"],
  ["Howard University", "howard.edu", "DC", 10000, 0.53, "Test Optional"],
  ["Seton Hall University", "shu.edu", "NJ", 6200, 0.60, "Test Optional"],
  ["Loyola University Maryland", "loyola.edu", "MD", 4200, 0.75, "Test Optional"],
  ["Drexel University", "drexel.edu", "PA", 13500, 0.78, "Test Optional"],
  ["Radford University", "radford.edu", "VA", 7500, 0.90, "Test Optional"],
  ["Princeton University", "princeton.edu", "NJ", 5600, 0.04, "Test Optional"],
  ["Hofstra University", "hofstra.edu", "NY", 6500, 0.78, "Test Optional"],

  // South — Medium
  ["Vanderbilt University", "vanderbilt.edu", "TN", 7100, 0.06, "Test Optional"],
  ["Rice University", "rice.edu", "TX", 4500, 0.09, "Test Optional"],
  ["Emory University", "emory.edu", "GA", 7100, 0.13, "Test Optional"],
  ["Wake Forest University", "wfu.edu", "NC", 5500, 0.22, "Test Optional"],
  ["Tulane University", "tulane.edu", "LA", 8500, 0.15, "Test Optional"],
  ["SMU", "smu.edu", "TX", 7100, 0.53, "Test Optional"],
  ["TCU", "tcu.edu", "TX", 10000, 0.48, "Test Optional"],
  ["University of Tampa", "ut.edu", "FL", 10000, 0.55, "Test Optional"],
  ["Belmont University", "belmont.edu", "TN", 7000, 0.80, "Test Optional"],
  ["Elon University", "elon.edu", "NC", 7000, 0.72, "Test Optional"],

  // Midwest — Medium
  ["University of Notre Dame", "nd.edu", "IN", 9000, 0.13, "Test Optional"],
  ["Washington University in St. Louis", "wustl.edu", "MO", 8000, 0.12, "Test Optional"],
  ["Marquette University", "marquette.edu", "WI", 8200, 0.82, "Test Optional"],
  ["Butler University", "butler.edu", "IN", 5000, 0.65, "Test Optional"],
  ["University of Dayton", "udayton.edu", "OH", 8500, 0.68, "Test Optional"],
  ["Creighton University", "creighton.edu", "NE", 4500, 0.65, "Test Optional"],
  ["Xavier University", "xavier.edu", "OH", 5200, 0.78, "Test Optional"],
  ["DePaul University", "depaul.edu", "IL", 13000, 0.70, "Test Optional"],
  ["University of Chicago", "uchicago.edu", "IL", 7500, 0.05, "Test Required"],
  ["Loyola University Chicago", "luc.edu", "IL", 12000, 0.67, "Test Optional"],
  ["Drake University", "drake.edu", "IA", 5000, 0.68, "Test Optional"],
  ["Bradley University", "bradley.edu", "IL", 5000, 0.72, "Test Optional"],
  ["Valparaiso University", "valpo.edu", "IN", 4500, 0.82, "Test Optional"],

  // West — Medium
  ["California Institute of Technology", "caltech.edu", "CA", 1000, 0.03, "Test Required"],
  ["Stanford University", "stanford.edu", "CA", 8100, 0.04, "Test Required"],
  ["Santa Clara University", "scu.edu", "CA", 6200, 0.49, "Test Optional"],
  ["Pepperdine University", "pepperdine.edu", "CA", 5500, 0.37, "Test Optional"],
  ["Loyola Marymount University", "lmu.edu", "CA", 7100, 0.45, "Test Optional"],
  ["University of San Diego", "sandiego.edu", "CA", 6200, 0.48, "Test Optional"],
  ["University of Denver", "du.edu", "CO", 6000, 0.63, "Test Optional"],
  ["Chapman University", "chapman.edu", "CA", 8500, 0.58, "Test Optional"],
  ["University of Portland", "up.edu", "OR", 4200, 0.72, "Test Optional"],
  ["Seattle University", "seattleu.edu", "WA", 4500, 0.78, "Test Optional"],
  ["University of San Francisco", "usfca.edu", "CA", 6800, 0.68, "Test Optional"],
  ["Pace University", "pace.edu", "NY", 8500, 0.80, "Test Optional"],

  // ═══════════════════════════════════════════════════════════════════════════
  // LARGE (15,000–29,999 undergrads)
  // ═══════════════════════════════════════════════════════════════════════════

  // Northeast — Large
  ["Harvard University", "harvard.edu", "MA", 21000, 0.03, "Test Required"],
  ["Columbia University", "columbia.edu", "NY", 23000, 0.04, "Test Optional"],
  ["Cornell University", "cornell.edu", "NY", 15000, 0.09, "Test Optional"],
  ["New York University", "nyu.edu", "NY", 28000, 0.13, "Test Optional"],
  ["Boston University", "bu.edu", "MA", 18000, 0.14, "Test Optional"],
  ["University of Connecticut", "uconn.edu", "CT", 19000, 0.56, "Test Optional"],
  ["University of New Hampshire", "unh.edu", "NH", 15000, 0.78, "Test Optional"],
  ["University of Vermont", "uvm.edu", "VT", 12000, 0.58, "Test Optional"],
  ["Stony Brook University", "stonybrook.edu", "NY", 18000, 0.49, "Test Optional"],
  ["University at Buffalo", "buffalo.edu", "NY", 22000, 0.60, "Test Optional"],
  ["Binghamton University", "binghamton.edu", "NY", 15000, 0.38, "Test Optional"],

  // Mid-Atlantic — Large
  ["University of Pennsylvania", "upenn.edu", "PA", 22000, 0.06, "Test Optional"],
  ["Johns Hopkins University", "jhu.edu", "MD", 17000, 0.08, "Test Optional"],
  ["University of Virginia", "virginia.edu", "VA", 17500, 0.19, "Test Required"],
  ["George Washington University", "gwu.edu", "DC", 15000, 0.44, "Test Optional"],
  ["University of Maryland College Park", "umd.edu", "MD", 30000, 0.45, "Test Required"],
  ["University of Pittsburgh", "pitt.edu", "PA", 20000, 0.42, "Test Required"],
  ["University of Delaware", "udel.edu", "DE", 19000, 0.60, "Test Optional"],
  ["Virginia Tech", "vt.edu", "VA", 28000, 0.57, "Test Required"],
  ["James Madison University", "jmu.edu", "VA", 22000, 0.76, "Test Optional"],
  ["Old Dominion University", "odu.edu", "VA", 20000, 0.83, "Test Optional"],
  ["George Mason University", "gmu.edu", "VA", 27000, 0.89, "Test Required"],
  ["West Virginia University", "wvu.edu", "WV", 22000, 0.85, "Test Optional"],
  ["Towson University", "towson.edu", "MD", 19000, 0.78, "Test Optional"],
  ["Syracuse University", "syracuse.edu", "NY", 16000, 0.53, "Test Optional"],
  ["Fordham University", "fordham.edu", "NY", 10000, 0.46, "Test Optional"],

  // South — Large
  ["Duke University", "duke.edu", "NC", 16000, 0.07, "Test Optional"],
  ["University of Miami", "miami.edu", "FL", 19000, 0.19, "Test Optional"],
  ["Clemson University", "clemson.edu", "SC", 22000, 0.38, "Test Required"],
  ["University of Alabama", "ua.edu", "AL", 29000, 0.74, "Test Optional"],
  ["University of Mississippi", "olemiss.edu", "MS", 18000, 0.88, "Test Optional"],
  ["University of Kentucky", "uky.edu", "KY", 22000, 0.90, "Test Required"],
  ["Appalachian State University", "appstate.edu", "NC", 19000, 0.72, "Test Optional"],
  ["University of South Carolina", "sc.edu", "SC", 27000, 0.80, "Test Required"],
  ["Baylor University", "baylor.edu", "TX", 15000, 0.52, "Test Optional"],
  ["University of Arkansas", "uark.edu", "AR", 23000, 0.80, "Test Optional"],

  // Midwest — Large
  ["Northwestern University", "northwestern.edu", "IL", 22000, 0.07, "Test Required"],
  ["University of Oregon", "uoregon.edu", "OR", 19000, 0.82, "Test Optional"],
  ["Miami University Ohio", "miamioh.edu", "OH", 17000, 0.65, "Test Optional"],

  // West — Large
  ["University of Southern California", "usc.edu", "CA", 21000, 0.10, "Test Optional"],
  ["University of Washington", "uw.edu", "WA", 28000, 0.48, "Test Optional"],
  ["University of California Santa Barbara", "ucsb.edu", "CA", 23000, 0.26, "Test Blind"],
  ["University of Colorado Boulder", "colorado.edu", "CO", 29000, 0.81, "Test Optional"],
  ["Washington State University", "wsu.edu", "WA", 25000, 0.83, "Test Optional"],
  ["University of Nevada Reno", "unr.edu", "NV", 18000, 0.85, "Test Optional"],
  ["University of Nevada Las Vegas", "unlv.edu", "NV", 22000, 0.82, "Test Optional"],
  ["University of New Mexico", "unm.edu", "NM", 18000, 0.85, "Test Optional"],
  ["Boise State University", "boisestate.edu", "ID", 20000, 0.82, "Test Optional"],
  ["University of Hawaii Manoa", "hawaii.edu", "HI", 15000, 0.80, "Test Optional"],
  ["Northern Arizona University", "nau.edu", "AZ", 22000, 0.85, "Test Optional"],
  ["University of Montana", "umt.edu", "MT", 8000, 0.92, "Test Optional"],
  ["San Diego State University", "sdsu.edu", "CA", 29000, 0.38, "Test Optional"],

  // ═══════════════════════════════════════════════════════════════════════════
  // MEGA (30,000+ undergrads)
  // ═══════════════════════════════════════════════════════════════════════════

  // Northeast — Mega
  ["University of Massachusetts Amherst", "umass.edu", "MA", 30000, 0.58, "Test Optional"],
  ["Rutgers University", "rutgers.edu", "NJ", 50000, 0.61, "Test Required"],

  // Mid-Atlantic — Mega
  ["Penn State University", "psu.edu", "PA", 46000, 0.55, "Test Required"],
  ["Temple University", "temple.edu", "PA", 30000, 0.80, "Test Optional"],
  ["Virginia Commonwealth University", "vcu.edu", "VA", 31000, 0.88, "Test Optional"],

  // South — Mega
  ["University of Texas at Austin", "utexas.edu", "TX", 51000, 0.31, "Test Required"],
  ["Texas A&M University", "tamu.edu", "TX", 65000, 0.63, "Test Required"],
  ["University of Florida", "ufl.edu", "FL", 52000, 0.25, "Test Required"],
  ["Florida State University", "fsu.edu", "FL", 42000, 0.25, "Test Required"],
  ["University of Georgia", "uga.edu", "GA", 40000, 0.43, "Test Required"],
  ["Georgia Institute of Technology", "gatech.edu", "GA", 40000, 0.17, "Test Required"],
  ["University of North Carolina at Chapel Hill", "unc.edu", "NC", 30000, 0.19, "Test Required"],
  ["NC State University", "ncsu.edu", "NC", 35000, 0.47, "Test Optional"],
  ["University of South Florida", "usf.edu", "FL", 50000, 0.45, "Test Optional"],
  ["University of Central Florida", "ucf.edu", "FL", 58000, 0.42, "Test Optional"],
  ["University of Tennessee", "utk.edu", "TN", 30000, 0.83, "Test Required"],
  ["Auburn University", "auburn.edu", "AL", 31000, 0.82, "Test Required"],
  ["Louisiana State University", "lsu.edu", "LA", 35000, 0.76, "Test Required"],
  ["University of North Texas", "unt.edu", "TX", 38000, 0.82, "Test Optional"],
  ["University of Texas San Antonio", "utsa.edu", "TX", 32000, 0.85, "Test Optional"],
  ["Texas State University", "txstate.edu", "TX", 35000, 0.84, "Test Optional"],
  ["Texas Tech University", "ttu.edu", "TX", 38000, 0.72, "Test Optional"],
  ["University of Houston", "uh.edu", "TX", 36000, 0.65, "Test Optional"],

  // Midwest — Mega
  ["Ohio State University", "osu.edu", "OH", 60000, 0.53, "Test Required"],
  ["University of Michigan", "umich.edu", "MI", 46000, 0.18, "Test Required"],
  ["University of Wisconsin Madison", "wisc.edu", "WI", 44000, 0.43, "Test Required"],
  ["University of Illinois Urbana-Champaign", "illinois.edu", "IL", 52000, 0.44, "Test Required"],
  ["Purdue University", "purdue.edu", "IN", 50000, 0.53, "Test Required"],
  ["Indiana University Bloomington", "iu.edu", "IN", 45000, 0.80, "Test Optional"],
  ["Michigan State University", "msu.edu", "MI", 49000, 0.83, "Test Optional"],
  ["University of Minnesota", "umn.edu", "MN", 51000, 0.75, "Test Optional"],
  ["University of Iowa", "uiowa.edu", "IA", 30000, 0.84, "Test Optional"],
  ["Iowa State University", "iastate.edu", "IA", 32000, 0.90, "Test Optional"],
  ["University of Kansas", "ku.edu", "KS", 27000, 0.88, "Test Optional"],
  ["Kansas State University", "kstate.edu", "KS", 21000, 0.92, "Test Optional"],
  ["University of Nebraska Lincoln", "unl.edu", "NE", 25000, 0.80, "Test Optional"],
  ["University of Missouri", "missouri.edu", "MO", 30000, 0.78, "Test Optional"],

  // West — Mega
  ["University of California Berkeley", "berkeley.edu", "CA", 42000, 0.12, "Test Blind"],
  ["University of California Los Angeles", "ucla.edu", "CA", 45000, 0.09, "Test Blind"],
  ["University of California San Diego", "ucsd.edu", "CA", 40000, 0.24, "Test Blind"],
  ["University of California Davis", "ucdavis.edu", "CA", 38000, 0.37, "Test Blind"],
  ["University of California Irvine", "uci.edu", "CA", 36000, 0.21, "Test Blind"],
  ["University of California Santa Cruz", "ucsc.edu", "CA", 18000, 0.47, "Test Blind"],
  ["Arizona State University", "asu.edu", "AZ", 65000, 0.88, "Test Optional"],
  ["University of Arizona", "arizona.edu", "AZ", 46000, 0.86, "Test Optional"],
  ["Oregon State University", "oregonstate.edu", "OR", 32000, 0.79, "Test Optional"],
  ["Colorado State University", "colostate.edu", "CO", 34000, 0.84, "Test Optional"],
  ["University of Utah", "utah.edu", "UT", 33000, 0.82, "Test Optional"],
  ["Utah State University", "usu.edu", "UT", 30000, 0.88, "Test Optional"],
  ["San Jose State University", "sjsu.edu", "CA", 34000, 0.62, "Test Optional"],
  ["Cal Poly San Luis Obispo", "calpoly.edu", "CA", 22000, 0.30, "Test Optional"],

  // ═══════════════════════════════════════════════════════════════════════════
  // ADDITIONAL SCHOOLS (expanded to 500+)
  // ═══════════════════════════════════════════════════════════════════════════

  // ── Additional Micro (<2,000) ─────────────────────────────────────────────
  ["Fisk University", "fisk.edu", "TN", 800, 0.40, "Test Optional"],
  ["Tougaloo College", "tougaloo.edu", "MS", 700, 0.55, "Test Optional"],
  ["Dillard University", "dillard.edu", "LA", 1200, 0.55, "Test Optional"],
  ["Talladega College", "talladega.edu", "AL", 700, 0.55, "Test Optional"],
  ["Berea College", "berea.edu", "KY", 1600, 0.32, "Test Optional"],
  ["New College of Florida", "ncf.edu", "FL", 700, 0.68, "Test Optional"],
  ["College of the Atlantic", "coa.edu", "ME", 350, 0.72, "Test Optional"],
  ["Warren Wilson College", "warren-wilson.edu", "NC", 700, 0.72, "Test Optional"],
  ["Centenary College of Louisiana", "centenary.edu", "LA", 900, 0.62, "Test Optional"],
  ["Virginia Wesleyan University", "vwu.edu", "VA", 1500, 0.78, "Test Optional"],
  ["Mary Baldwin University", "marybaldwin.edu", "VA", 1200, 0.85, "Test Optional"],
  ["Illinois Wesleyan University", "iwu.edu", "IL", 1600, 0.55, "Test Optional"],
  ["Huston-Tillotson University", "htu.edu", "TX", 1000, 0.65, "Test Optional"],
  ["Nebraska Wesleyan University", "nebrwesleyan.edu", "NE", 1800, 0.72, "Test Optional"],
  ["Maryville College", "maryvillecollege.edu", "TN", 1000, 0.72, "Test Optional"],
  ["Franklin College", "franklincollege.edu", "IN", 1000, 0.72, "Test Optional"],
  ["Converse University", "converse.edu", "SC", 800, 0.78, "Test Optional"],
  ["Morningside University", "morningside.edu", "IA", 1300, 0.65, "Test Optional"],
  ["Lees-McRae College", "lmc.edu", "NC", 800, 0.72, "Test Optional"],
  ["Coker University", "coker.edu", "SC", 1200, 0.62, "Test Optional"],
  ["Rust College", "rustcollege.edu", "MS", 600, 0.50, "Test Optional"],
  ["Stillman College", "stillman.edu", "AL", 700, 0.65, "Test Optional"],
  ["Philander Smith University", "philander.edu", "AR", 800, 0.60, "Test Optional"],
  ["Claflin University", "claflin.edu", "SC", 1900, 0.52, "Test Optional"],
  ["College of the Ozarks", "cofo.edu", "MO", 1500, 0.12, "Test Optional"],
  ["Alice Lloyd College", "alc.edu", "KY", 600, 0.55, "Test Optional"],
  ["Catawba College", "catawba.edu", "NC", 1200, 0.62, "Test Optional"],

  // ── Additional Small (2,000–4,999) ────────────────────────────────────────
  // HBCUs
  ["Spelman College", "spelman.edu", "GA", 2100, 0.35, "Test Optional"],
  ["Morehouse College", "morehouse.edu", "GA", 2600, 0.50, "Test Optional"],
  ["Clark Atlanta University", "cau.edu", "GA", 3000, 0.52, "Test Optional"],
  ["Tuskegee University", "tuskegee.edu", "AL", 2800, 0.48, "Test Optional"],
  ["Hampton University", "hamptonu.edu", "VA", 3500, 0.48, "Test Optional"],
  ["Xavier University of Louisiana", "xula.edu", "LA", 2400, 0.62, "Test Optional"],
  ["Norfolk State University", "nsu.edu", "VA", 3800, 0.82, "Test Optional"],
  ["Delaware State University", "desu.edu", "DE", 4200, 0.55, "Test Optional"],
  ["Lincoln University", "lincoln.edu", "PA", 2000, 0.72, "Test Optional"],
  ["Bethune-Cookman University", "cookman.edu", "FL", 2500, 0.58, "Test Optional"],
  ["Bowie State University", "bowiestate.edu", "MD", 4500, 0.52, "Test Optional"],
  ["Coppin State University", "coppin.edu", "MD", 2000, 0.62, "Test Optional"],
  ["South Carolina State University", "scsu.edu", "SC", 2500, 0.82, "Test Optional"],
  ["Alabama State University", "alasu.edu", "AL", 3200, 0.72, "Test Optional"],
  ["Alcorn State University", "alcorn.edu", "MS", 2800, 0.72, "Test Optional"],
  // Women's colleges
  ["Smith College", "smith.edu", "MA", 2500, 0.25, "Test Optional"],
  ["Mount Holyoke College", "mtholyoke.edu", "MA", 2200, 0.52, "Test Optional"],
  // Northeast private
  ["Babson College", "babson.edu", "MA", 2500, 0.20, "Test Optional"],
  ["Bentley University", "bentley.edu", "MA", 4200, 0.45, "Test Optional"],
  ["Emerson College", "emerson.edu", "MA", 3800, 0.32, "Test Optional"],
  ["Clark University", "clarku.edu", "MA", 2400, 0.52, "Test Optional"],
  ["Assumption University", "assumption.edu", "MA", 2000, 0.78, "Test Optional"],
  ["Wentworth Institute of Technology", "wit.edu", "MA", 3500, 0.82, "Test Optional"],
  ["Worcester Polytechnic Institute", "wpi.edu", "MA", 4900, 0.52, "Test Optional"],
  ["Salve Regina University", "salve.edu", "RI", 2500, 0.72, "Test Optional"],
  ["Roger Williams University", "rwu.edu", "RI", 4000, 0.82, "Test Optional"],
  ["Saint Michael's College", "smcvt.edu", "VT", 2000, 0.78, "Test Optional"],
  ["Champlain College", "champlain.edu", "VT", 2500, 0.72, "Test Optional"],
  ["Saint Anselm College", "anselm.edu", "NH", 2000, 0.78, "Test Optional"],
  ["Le Moyne University", "lemoyne.edu", "NY", 3000, 0.72, "Test Optional"],
  ["Canisius University", "canisius.edu", "NY", 2200, 0.78, "Test Optional"],
  ["Manhattan College", "manhattan.edu", "NY", 3500, 0.72, "Test Optional"],
  ["Wagner College", "wagner.edu", "NY", 2000, 0.72, "Test Optional"],
  ["Moravian University", "moravian.edu", "PA", 2000, 0.78, "Test Optional"],
  ["Clarkson University", "clarkson.edu", "NY", 3500, 0.72, "Test Optional"],
  ["Stevens Institute of Technology", "stevens.edu", "NJ", 4000, 0.40, "Test Optional"],
  ["St. Bonaventure University", "sbu.edu", "NY", 2000, 0.72, "Test Optional"],
  ["Niagara University", "niagara.edu", "NY", 3000, 0.82, "Test Optional"],
  ["La Salle University", "lasalle.edu", "PA", 4000, 0.78, "Test Optional"],
  // Mid-Atlantic & South private
  ["University of Lynchburg", "lynchburg.edu", "VA", 2500, 0.72, "Test Optional"],
  ["Jacksonville University", "ju.edu", "FL", 2800, 0.72, "Test Optional"],
  ["Lipscomb University", "lipscomb.edu", "TN", 3200, 0.62, "Test Optional"],
  ["Bellarmine University", "bellarmine.edu", "KY", 2800, 0.72, "Test Optional"],
  ["Anderson University", "andersonuniversity.edu", "SC", 3000, 0.62, "Test Optional"],
  ["Harding University", "harding.edu", "AR", 3500, 0.72, "Test Optional"],
  ["Spring Hill College", "shc.edu", "AL", 2000, 0.82, "Test Optional"],
  ["Milligan University", "milligan.edu", "TN", 2000, 0.72, "Test Optional"],
  ["UNC Asheville", "unca.edu", "NC", 3500, 0.78, "Test Optional"],
  // Midwest private
  ["Rose-Hulman Institute of Technology", "rose-hulman.edu", "IN", 2000, 0.68, "Test Optional"],
  ["University of Evansville", "evansville.edu", "IN", 2200, 0.72, "Test Optional"],
  ["Truman State University", "truman.edu", "MO", 4000, 0.72, "Test Optional"],
  ["John Carroll University", "jcu.edu", "OH", 2800, 0.82, "Test Optional"],
  ["Capital University", "capital.edu", "OH", 2800, 0.72, "Test Optional"],
  ["Otterbein University", "otterbein.edu", "OH", 2800, 0.72, "Test Optional"],
  ["Baldwin Wallace University", "bw.edu", "OH", 3000, 0.72, "Test Optional"],
  ["Concordia College", "concordiacollege.edu", "MN", 2000, 0.72, "Test Optional"],
  ["Rockhurst University", "rockhurst.edu", "MO", 2500, 0.72, "Test Optional"],
  ["North Central College", "northcentralcollege.edu", "IL", 3000, 0.72, "Test Optional"],
  ["Adrian College", "adrian.edu", "MI", 2000, 0.78, "Test Optional"],
  // South — Oklahoma & Texas
  ["Oklahoma City University", "okcu.edu", "OK", 2000, 0.62, "Test Optional"],
  ["University of Tulsa", "utulsa.edu", "OK", 3200, 0.65, "Test Optional"],
  ["Abilene Christian University", "acu.edu", "TX", 3500, 0.58, "Test Optional"],
  ["St. Edward's University", "stedwards.edu", "TX", 3500, 0.78, "Test Optional"],
  ["University of Dallas", "udallas.edu", "TX", 2500, 0.72, "Test Optional"],
  ["Texas Wesleyan University", "txwes.edu", "TX", 2000, 0.55, "Test Optional"],
  ["Ouachita Baptist University", "obu.edu", "AR", 2000, 0.72, "Test Optional"],
  ["Mississippi College", "mc.edu", "MS", 3500, 0.45, "Test Optional"],
  // West
  ["Seattle Pacific University", "spu.edu", "WA", 3000, 0.82, "Test Optional"],
  ["Saint Mary's College of California", "stmarys-ca.edu", "CA", 2800, 0.72, "Test Optional"],
  ["Regis University", "regis.edu", "CO", 3000, 0.72, "Test Optional"],
  ["College of Idaho", "collegeofidaho.edu", "ID", 2000, 0.72, "Test Optional"],
  ["University of the Pacific", "pacific.edu", "CA", 3500, 0.68, "Test Optional"],
  ["Augustana University", "augie.edu", "SD", 2000, 0.72, "Test Optional"],

  // ── Additional Medium (5,000–14,999) ──────────────────────────────────────
  // HBCUs
  ["Florida A&M University", "famu.edu", "FL", 8000, 0.38, "Test Optional"],
  ["North Carolina A&T State University", "ncat.edu", "NC", 12000, 0.52, "Test Optional"],
  ["Prairie View A&M University", "pvamu.edu", "TX", 8000, 0.62, "Test Optional"],
  ["Tennessee State University", "tnstate.edu", "TN", 6000, 0.72, "Test Optional"],
  ["Southern University", "subr.edu", "LA", 5500, 0.55, "Test Optional"],
  ["Grambling State University", "gram.edu", "LA", 5000, 0.55, "Test Optional"],
  ["Morgan State University", "morgan.edu", "MD", 5000, 0.62, "Test Optional"],
  ["Alabama A&M University", "aamu.edu", "AL", 5000, 0.45, "Test Optional"],
  ["Jackson State University", "jsums.edu", "MS", 5000, 0.68, "Test Optional"],
  // Northeast & Mid-Atlantic
  ["Rensselaer Polytechnic Institute", "rpi.edu", "NY", 5800, 0.50, "Test Optional"],
  ["Rochester Institute of Technology", "rit.edu", "NY", 13000, 0.65, "Test Optional"],
  ["University of Rochester", "rochester.edu", "NY", 6800, 0.36, "Test Optional"],
  ["Brandeis University", "brandeis.edu", "MA", 5800, 0.35, "Test Optional"],
  ["Sacred Heart University", "sacredheart.edu", "CT", 6500, 0.68, "Test Optional"],
  ["SUNY Geneseo", "geneseo.edu", "NY", 5000, 0.55, "Test Optional"],
  ["SUNY New Paltz", "newpaltz.edu", "NY", 8000, 0.48, "Test Optional"],
  ["University at Albany SUNY", "albany.edu", "NY", 13000, 0.55, "Test Optional"],
  ["SUNY Cortland", "cortland.edu", "NY", 6500, 0.58, "Test Optional"],
  ["SUNY Oswego", "oswego.edu", "NY", 7000, 0.62, "Test Optional"],
  ["University of Scranton", "scranton.edu", "PA", 5200, 0.72, "Test Optional"],
  ["Saint Joseph's University", "sju.edu", "PA", 6500, 0.78, "Test Optional"],
  ["Duquesne University", "duq.edu", "PA", 5800, 0.72, "Test Optional"],
  ["Rowan University", "rowan.edu", "NJ", 13000, 0.78, "Test Optional"],
  ["NJIT", "njit.edu", "NJ", 8000, 0.62, "Test Optional"],
  ["Monmouth University", "monmouth.edu", "NJ", 5500, 0.78, "Test Optional"],
  ["Rider University", "rider.edu", "NJ", 5000, 0.78, "Test Optional"],
  ["Iona University", "iona.edu", "NY", 5000, 0.78, "Test Optional"],
  ["St. John's University", "stjohns.edu", "NY", 14000, 0.72, "Test Optional"],
  ["University of Mary Washington", "umw.edu", "VA", 5000, 0.82, "Test Optional"],
  ["Longwood University", "longwood.edu", "VA", 5000, 0.82, "Test Optional"],
  // South
  ["High Point University", "highpoint.edu", "NC", 5500, 0.72, "Test Optional"],
  ["Campbell University", "campbell.edu", "NC", 5000, 0.72, "Test Optional"],
  ["UNC Greensboro", "uncg.edu", "NC", 14000, 0.82, "Test Optional"],
  ["Western Carolina University", "wcu.edu", "NC", 10000, 0.72, "Test Optional"],
  ["Winthrop University", "winthrop.edu", "SC", 6000, 0.72, "Test Optional"],
  ["Coastal Carolina University", "coastal.edu", "SC", 10000, 0.65, "Test Optional"],
  ["Western Kentucky University", "wku.edu", "KY", 14000, 0.85, "Test Optional"],
  ["Eastern Kentucky University", "eku.edu", "KY", 13000, 0.82, "Test Optional"],
  ["Murray State University", "murraystate.edu", "KY", 8000, 0.82, "Test Optional"],
  ["Northern Kentucky University", "nku.edu", "KY", 12000, 0.88, "Test Optional"],
  ["University of Alabama Huntsville", "uah.edu", "AL", 8000, 0.78, "Test Optional"],
  ["Stephen F. Austin State University", "sfasu.edu", "TX", 12000, 0.82, "Test Optional"],
  ["Lamar University", "lamar.edu", "TX", 12000, 0.85, "Test Optional"],
  ["Loyola University New Orleans", "loyno.edu", "LA", 5000, 0.78, "Test Optional"],
  // Midwest
  ["Case Western Reserve University", "case.edu", "OH", 5400, 0.30, "Test Optional"],
  ["Illinois Institute of Technology", "iit.edu", "IL", 6500, 0.52, "Test Optional"],
  ["University of Saint Thomas", "stthomas.edu", "MN", 10000, 0.82, "Test Optional"],
  ["Saint Louis University", "slu.edu", "MO", 8000, 0.58, "Test Optional"],
  ["Youngstown State University", "ysu.edu", "OH", 10000, 0.88, "Test Optional"],
  ["Wright State University", "wright.edu", "OH", 10000, 0.88, "Test Optional"],
  ["Cleveland State University", "csuohio.edu", "OH", 10000, 0.92, "Test Optional"],
  ["University of Toledo", "utoledo.edu", "OH", 14000, 0.88, "Test Optional"],
  ["University of Northern Iowa", "uni.edu", "IA", 9000, 0.82, "Test Optional"],
  // West & other
  ["Portland State University", "pdx.edu", "OR", 14000, 0.92, "Test Optional"],
  ["Biola University", "biola.edu", "CA", 5500, 0.62, "Test Optional"],
  ["Sonoma State University", "sonoma.edu", "CA", 6000, 0.92, "Test Optional"],
  ["University of Wyoming", "uwyo.edu", "WY", 10000, 0.92, "Test Optional"],
  ["University of Idaho", "uidaho.edu", "ID", 10000, 0.78, "Test Optional"],
  ["University of Alaska Fairbanks", "uaf.edu", "AK", 5000, 0.72, "Test Optional"],
  ["University of North Dakota", "und.edu", "ND", 10000, 0.82, "Test Optional"],
  ["University of South Dakota", "usd.edu", "SD", 7000, 0.85, "Test Optional"],
  ["North Dakota State University", "ndsu.edu", "ND", 12000, 0.88, "Test Optional"],
  ["South Dakota State University", "sdstate.edu", "SD", 10000, 0.85, "Test Optional"],

  // ── Additional Large (15,000–29,999) ──────────────────────────────────────
  ["University of Oklahoma", "ou.edu", "OK", 24000, 0.83, "Test Optional"],
  ["Oklahoma State University", "okstate.edu", "OK", 21000, 0.75, "Test Optional"],
  ["UNC Charlotte", "charlotte.edu", "NC", 23000, 0.75, "Test Optional"],
  ["UNC Wilmington", "uncw.edu", "NC", 15000, 0.62, "Test Optional"],
  ["East Carolina University", "ecu.edu", "NC", 23000, 0.78, "Test Optional"],
  ["Kennesaw State University", "kennesaw.edu", "GA", 28000, 0.85, "Test Optional"],
  ["Georgia State University", "gsu.edu", "GA", 28000, 0.78, "Test Optional"],
  ["Middle Tennessee State University", "mtsu.edu", "TN", 19000, 0.85, "Test Optional"],
  ["University of Memphis", "memphis.edu", "TN", 18000, 0.82, "Test Optional"],
  ["University of Louisville", "louisville.edu", "KY", 16000, 0.72, "Test Optional"],
  ["University of South Alabama", "southalabama.edu", "AL", 15000, 0.82, "Test Optional"],
  ["Troy University", "troy.edu", "AL", 15000, 0.72, "Test Optional"],
  ["University of Alabama at Birmingham", "uab.edu", "AL", 15000, 0.82, "Test Optional"],
  ["Sam Houston State University", "shsu.edu", "TX", 20000, 0.82, "Test Optional"],
  ["Texas Woman's University", "twu.edu", "TX", 15000, 0.78, "Test Optional"],
  ["University of North Florida", "unf.edu", "FL", 15000, 0.72, "Test Optional"],
  ["Florida Gulf Coast University", "fgcu.edu", "FL", 15000, 0.72, "Test Optional"],
  ["Wichita State University", "wichita.edu", "KS", 15000, 0.92, "Test Optional"],
  ["University of Wisconsin Milwaukee", "uwm.edu", "WI", 20000, 0.88, "Test Optional"],
  ["Western Michigan University", "wmich.edu", "MI", 16000, 0.82, "Test Optional"],
  ["Central Michigan University", "cmich.edu", "MI", 15000, 0.78, "Test Optional"],
  ["Eastern Michigan University", "emich.edu", "MI", 15000, 0.82, "Test Optional"],
  ["Ball State University", "bsu.edu", "IN", 16000, 0.78, "Test Optional"],
  ["Missouri State University", "missouristate.edu", "MO", 20000, 0.82, "Test Optional"],
  ["Southern Illinois University Carbondale", "siu.edu", "IL", 15000, 0.85, "Test Optional"],
  ["Northern Illinois University", "niu.edu", "IL", 16000, 0.55, "Test Optional"],
  ["Illinois State University", "illinoisstate.edu", "IL", 21000, 0.72, "Test Optional"],
  ["Bowling Green State University", "bgsu.edu", "OH", 15000, 0.82, "Test Optional"],
  ["Kent State University", "kent.edu", "OH", 21000, 0.85, "Test Optional"],
  ["University of Akron", "uakron.edu", "OH", 15000, 0.88, "Test Optional"],
  ["Montana State University", "montana.edu", "MT", 16000, 0.82, "Test Optional"],
  ["University of Northern Colorado", "unco.edu", "CO", 15000, 0.88, "Test Optional"],
  ["Cal State Long Beach", "csulb.edu", "CA", 29000, 0.30, "Test Optional"],
  ["Cal State Fullerton", "fullerton.edu", "CA", 28000, 0.48, "Test Optional"],
  ["Cal State Northridge", "csun.edu", "CA", 27000, 0.52, "Test Optional"],
  ["Cal State Sacramento", "csus.edu", "CA", 25000, 0.68, "Test Optional"],
  ["Cal Poly Pomona", "cpp.edu", "CA", 22000, 0.48, "Test Optional"],
  ["Fresno State", "fresnostate.edu", "CA", 22000, 0.62, "Test Optional"],
  ["San Francisco State University", "sfsu.edu", "CA", 22000, 0.72, "Test Optional"],

  // ── Additional Mega (30,000+) ─────────────────────────────────────────────
  ["Florida International University", "fiu.edu", "FL", 48000, 0.58, "Test Optional"],
  ["Florida Atlantic University", "fau.edu", "FL", 30000, 0.62, "Test Optional"],
  ["Georgia Southern University", "georgiasouthern.edu", "GA", 30000, 0.82, "Test Optional"],
  ["University of Cincinnati", "uc.edu", "OH", 36000, 0.82, "Test Optional"],
  ["Wayne State University", "wayne.edu", "MI", 30000, 0.78, "Test Optional"],

  // ═══════════════════════════════════════════════════════════════════════════
  // ART & DESIGN SCHOOLS
  // ═══════════════════════════════════════════════════════════════════════════
  ["Rhode Island School of Design", "risd.edu", "RI", 2000, 0.20, "Test Optional"],
  ["Pratt Institute", "pratt.edu", "NY", 3200, 0.42, "Test Optional"],
  ["Savannah College of Art and Design", "scad.edu", "GA", 11000, 0.90, "Test Optional"],
  ["California Institute of the Arts", "calarts.edu", "CA", 1000, 0.25, "Test Optional"],
  ["School of Visual Arts", "sva.edu", "NY", 3500, 0.68, "Test Optional"],
  ["The New School / Parsons", "newschool.edu", "NY", 7200, 0.52, "Test Optional"],
  ["ArtCenter College of Design", "artcenter.edu", "CA", 1900, 0.68, "Test Optional"],
  ["Maryland Institute College of Art", "mica.edu", "MD", 1600, 0.62, "Test Optional"],
  ["Ringling College of Art and Design", "ringling.edu", "FL", 1600, 0.72, "Test Optional"],
  ["California College of the Arts", "cca.edu", "CA", 1400, 0.78, "Test Optional"],
  ["Otis College of Art and Design", "otis.edu", "CA", 1000, 0.72, "Test Optional"],
  ["Cornish College of the Arts", "cornish.edu", "WA", 600, 0.78, "Test Optional"],
  ["School of the Art Institute of Chicago", "saic.edu", "IL", 2800, 0.58, "Test Optional"],
  ["Cooper Union", "cooper.edu", "NY", 900, 0.13, "Test Optional"],
  ["Massachusetts College of Art and Design", "massart.edu", "MA", 1800, 0.72, "Test Optional"],

  // ═══════════════════════════════════════════════════════════════════════════
  // MUSIC CONSERVATORIES
  // ═══════════════════════════════════════════════════════════════════════════
  ["Berklee College of Music", "berklee.edu", "MA", 4600, 0.42, "Test Optional"],
  ["New England Conservatory", "necmusic.edu", "MA", 400, 0.30, "Test Optional"],
  ["Manhattan School of Music", "msmnyc.edu", "NY", 400, 0.38, "Test Optional"],
  ["Juilliard School", "juilliard.edu", "NY", 500, 0.07, "Test Optional"],
  ["Curtis Institute of Music", "curtis.edu", "PA", 200, 0.04, "Test Optional"],
  ["San Francisco Conservatory of Music", "sfcm.edu", "CA", 250, 0.35, "Test Optional"],
  ["Cleveland Institute of Music", "cim.edu", "OH", 250, 0.30, "Test Optional"],
  ["Mannes School of Music", "newschool.edu/mannes", "NY", 300, 0.35, "Test Optional"],

  // ═══════════════════════════════════════════════════════════════════════════
  // ENGINEERING-FOCUSED (not already in database)
  // ═══════════════════════════════════════════════════════════════════════════
  ["Olin College of Engineering", "olin.edu", "MA", 400, 0.16, "Test Optional"],
  ["Colorado School of Mines", "mines.edu", "CO", 5400, 0.54, "Test Required"],
  ["Kettering University", "kettering.edu", "MI", 1600, 0.72, "Test Optional"],
  ["Milwaukee School of Engineering", "msoe.edu", "WI", 2400, 0.68, "Test Optional"],
  ["Webb Institute", "webb.edu", "NY", 100, 0.28, "Test Required"],

  // ═══════════════════════════════════════════════════════════════════════════
  // ADDITIONAL HBCUs (not already in database)
  // ═══════════════════════════════════════════════════════════════════════════
  ["Bennett College", "bennett.edu", "NC", 300, 0.55, "Test Optional"],
  ["Wilberforce University", "wilberforce.edu", "OH", 500, 0.65, "Test Optional"],
  ["Voorhees University", "voorhees.edu", "SC", 500, 0.72, "Test Optional"],
  ["Lane College", "lanecollege.edu", "TN", 1200, 0.55, "Test Optional"],
  ["Paine College", "paine.edu", "GA", 600, 0.40, "Test Optional"],
  ["Virginia Union University", "vuu.edu", "VA", 1200, 0.62, "Test Optional"],
  ["Virginia State University", "vsu.edu", "VA", 4000, 0.72, "Test Optional"],
  ["Savannah State University", "savannahstate.edu", "GA", 2800, 0.72, "Test Optional"],
  ["Fort Valley State University", "fvsu.edu", "GA", 2200, 0.62, "Test Optional"],
  ["Elizabeth City State University", "ecsu.edu", "NC", 1500, 0.72, "Test Optional"],
  ["Winston-Salem State University", "wssu.edu", "NC", 4500, 0.62, "Test Optional"],
  ["North Carolina Central University", "nccu.edu", "NC", 5500, 0.62, "Test Optional"],
  ["Kentucky State University", "kysu.edu", "KY", 2000, 0.65, "Test Optional"],
  ["Harris-Stowe State University", "hssu.edu", "MO", 1200, 0.72, "Test Optional"],
  ["Central State University", "centralstate.edu", "OH", 2000, 0.55, "Test Optional"],

  // ═══════════════════════════════════════════════════════════════════════════
  // ADDITIONAL WOMEN'S COLLEGES (not already in database)
  // ═══════════════════════════════════════════════════════════════════════════
  ["Simmons University", "simmons.edu", "MA", 1800, 0.72, "Test Optional"],
  ["Cottey College", "cottey.edu", "MO", 300, 0.72, "Test Optional"],
  ["Bay Path University", "baypath.edu", "MA", 1500, 0.78, "Test Optional"],
  ["Cedar Crest College", "cedarcrest.edu", "PA", 1000, 0.78, "Test Optional"],
  ["Alverno College", "alverno.edu", "WI", 1200, 0.78, "Test Optional"],
  ["Salem College", "salem.edu", "NC", 700, 0.72, "Test Optional"],
  ["Meredith College", "meredith.edu", "NC", 1600, 0.65, "Test Optional"],
  ["Stephens College", "stephens.edu", "MO", 700, 0.78, "Test Optional"],

  // ═══════════════════════════════════════════════════════════════════════════
  // ADDITIONAL LIBERAL ARTS
  // ═══════════════════════════════════════════════════════════════════════════
  ["Bard College", "bard.edu", "NY", 1900, 0.55, "Test Optional"],
  ["Thomas Aquinas College", "thomasaquinas.edu", "CA", 400, 0.72, "Test Optional"],
  ["Deep Springs College", "deepsprings.edu", "CA", 30, 0.07, "Test Optional"],
  ["Gordon College", "gordon.edu", "MA", 1500, 0.78, "Test Optional"],
  ["Covenant College", "covenant.edu", "GA", 900, 0.72, "Test Optional"],
  ["Calvin University", "calvin.edu", "MI", 3200, 0.72, "Test Optional"],
  ["George Fox University", "georgefox.edu", "OR", 2500, 0.82, "Test Optional"],
  ["Franciscan University of Steubenville", "franciscan.edu", "OH", 2300, 0.78, "Test Optional"],
  ["Christendom College", "christendom.edu", "VA", 500, 0.78, "Test Optional"],

  // ═══════════════════════════════════════════════════════════════════════════
  // REGIONAL PUBLIC UNIVERSITIES
  // ═══════════════════════════════════════════════════════════════════════════

  // ── Northeast Regional Publics ──────────────────────────────────────────
  ["Keene State College", "keene.edu", "NH", 3200, 0.88, "Test Optional"],
  ["Plymouth State University", "plymouth.edu", "NH", 3800, 0.85, "Test Optional"],
  ["SUNY Plattsburgh", "plattsburgh.edu", "NY", 5000, 0.72, "Test Optional"],
  ["SUNY Fredonia", "fredonia.edu", "NY", 4000, 0.78, "Test Optional"],
  ["SUNY Brockport", "brockport.edu", "NY", 6500, 0.72, "Test Optional"],
  ["SUNY Oneonta", "oneonta.edu", "NY", 6000, 0.62, "Test Optional"],
  ["SUNY Potsdam", "potsdam.edu", "NY", 3000, 0.78, "Test Optional"],
  ["Bridgewater State University", "bridgew.edu", "MA", 9000, 0.88, "Test Optional"],
  ["Fitchburg State University", "fitchburgstate.edu", "MA", 4500, 0.88, "Test Optional"],
  ["Framingham State University", "framingham.edu", "MA", 4000, 0.85, "Test Optional"],
  ["Salem State University", "salemstate.edu", "MA", 6000, 0.85, "Test Optional"],
  ["Westfield State University", "westfield.ma.edu", "MA", 4000, 0.88, "Test Optional"],
  ["Worcester State University", "worcester.edu", "MA", 5000, 0.85, "Test Optional"],
  ["Rhode Island College", "ric.edu", "RI", 5500, 0.82, "Test Optional"],
  ["Western Connecticut State University", "wcsu.edu", "CT", 4500, 0.88, "Test Optional"],
  ["Southern Connecticut State University", "southernct.edu", "CT", 7500, 0.82, "Test Optional"],
  ["Central Connecticut State University", "ccsu.edu", "CT", 8500, 0.78, "Test Optional"],
  ["Eastern Connecticut State University", "easternct.edu", "CT", 4500, 0.82, "Test Optional"],
  ["CUNY Hunter College", "hunter.cuny.edu", "NY", 16000, 0.38, "Test Optional"],
  ["CUNY Baruch College", "baruch.cuny.edu", "NY", 15000, 0.42, "Test Optional"],
  ["CUNY City College", "ccny.cuny.edu", "NY", 13000, 0.52, "Test Optional"],

  // ── Mid-Atlantic Regional Publics ───────────────────────────────────────
  ["Shippensburg University", "ship.edu", "PA", 5000, 0.88, "Test Optional"],
  ["Millersville University", "millersville.edu", "PA", 6000, 0.82, "Test Optional"],
  ["Kutztown University", "kutztown.edu", "PA", 7000, 0.88, "Test Optional"],
  ["Slippery Rock University", "sru.edu", "PA", 7500, 0.78, "Test Optional"],
  ["Clarion University / PennWest Clarion", "pennwest.edu/clarion", "PA", 4000, 0.88, "Test Optional"],
  ["Edinboro University / PennWest Edinboro", "pennwest.edu/edinboro", "PA", 4000, 0.88, "Test Optional"],
  ["Frostburg State University", "frostburg.edu", "MD", 4000, 0.82, "Test Optional"],
  ["Salisbury University", "salisbury.edu", "MD", 7500, 0.62, "Test Optional"],
  ["Shepherd University", "shepherd.edu", "WV", 3000, 0.88, "Test Optional"],

  // ── South Regional Publics ──────────────────────────────────────────────
  ["Valdosta State University", "valdosta.edu", "GA", 9000, 0.82, "Test Optional"],
  ["Columbus State University", "columbusstate.edu", "GA", 7000, 0.78, "Test Optional"],
  ["Francis Marion University", "fmarion.edu", "SC", 3500, 0.82, "Test Optional"],
  ["Lander University", "lander.edu", "SC", 3200, 0.72, "Test Optional"],
  ["Jacksonville State University", "jsu.edu", "AL", 8500, 0.82, "Test Optional"],
  ["Austin Peay State University", "apsu.edu", "TN", 9000, 0.78, "Test Optional"],
  ["Tennessee Technological University", "tntech.edu", "TN", 9000, 0.82, "Test Optional"],
  ["East Tennessee State University", "etsu.edu", "TN", 11000, 0.85, "Test Optional"],
  ["Morehead State University", "moreheadstate.edu", "KY", 7000, 0.88, "Test Optional"],

  // ── Midwest Regional Publics ────────────────────────────────────────────
  ["Emporia State University", "emporia.edu", "KS", 4500, 0.88, "Test Optional"],
  ["Pittsburg State University", "pittstate.edu", "KS", 5500, 0.85, "Test Optional"],
  ["Fort Hays State University", "fhsu.edu", "KS", 5000, 0.88, "Test Optional"],
  ["Wayne State College", "wsc.edu", "NE", 3500, 0.88, "Test Optional"],
  ["Minot State University", "minotstateu.edu", "ND", 3000, 0.85, "Test Optional"],
  ["Bemidji State University", "bemidjistate.edu", "MN", 4500, 0.82, "Test Optional"],
  ["Minnesota State University Mankato", "mnsu.edu", "MN", 13000, 0.78, "Test Optional"],
  ["UW Oshkosh", "uwosh.edu", "WI", 10000, 0.82, "Test Optional"],
  ["UW La Crosse", "uwlax.edu", "WI", 10000, 0.72, "Test Optional"],
  ["UW Eau Claire", "uwec.edu", "WI", 10000, 0.78, "Test Optional"],
  ["UW Stout", "uwstout.edu", "WI", 7000, 0.88, "Test Optional"],
  ["UW Whitewater", "uww.edu", "WI", 10000, 0.82, "Test Optional"],
  ["Grand Valley State University", "gvsu.edu", "MI", 20000, 0.82, "Test Optional"],
  ["Ferris State University", "ferris.edu", "MI", 9000, 0.88, "Test Optional"],
  ["Saginaw Valley State University", "svsu.edu", "MI", 7000, 0.82, "Test Optional"],
  ["Lake Superior State University", "lssu.edu", "MI", 2000, 0.88, "Test Optional"],
  ["Indiana State University", "indstate.edu", "IN", 10000, 0.88, "Test Optional"],
  ["Southeast Missouri State University", "semo.edu", "MO", 8000, 0.88, "Test Optional"],
  ["Northwest Missouri State University", "nwmissouri.edu", "MO", 6000, 0.78, "Test Optional"],

  // ── West Regional Publics ───────────────────────────────────────────────
  ["Cal Poly Humboldt", "humboldt.edu", "CA", 6000, 0.82, "Test Optional"],
  ["CSU Bakersfield", "csub.edu", "CA", 10000, 0.82, "Test Optional"],
  ["CSU Stanislaus", "csustan.edu", "CA", 8000, 0.85, "Test Optional"],
  ["CSU Dominguez Hills", "csudh.edu", "CA", 15000, 0.82, "Test Optional"],
  ["CSU San Bernardino", "csusb.edu", "CA", 15000, 0.82, "Test Optional"],
  ["CSU East Bay", "csueastbay.edu", "CA", 13000, 0.78, "Test Optional"],
  ["Central Washington University", "cwu.edu", "WA", 10000, 0.85, "Test Optional"],
  ["Eastern Washington University", "ewu.edu", "WA", 10000, 0.88, "Test Optional"],
  ["Western Washington University", "wwu.edu", "WA", 14000, 0.72, "Test Optional"],
  ["Southern Oregon University", "sou.edu", "OR", 5000, 0.88, "Test Optional"],
  ["Eastern Oregon University", "eou.edu", "OR", 3000, 0.88, "Test Optional"],
  ["Western Oregon University", "wou.edu", "OR", 4000, 0.88, "Test Optional"],
  ["Adams State University", "adams.edu", "CO", 2500, 0.88, "Test Optional"],
  ["Fort Lewis College", "fortlewis.edu", "CO", 3000, 0.88, "Test Optional"],
  ["New Mexico State University", "nmsu.edu", "NM", 11000, 0.58, "Test Optional"],
  ["New Mexico Highlands University", "nmhu.edu", "NM", 2000, 0.88, "Test Optional"],

  // ═══════════════════════════════════════════════════════════════════════════
  // NURSING / BUSINESS / CJ / EDUCATION-STRONG
  // ═══════════════════════════════════════════════════════════════════════════
  ["Chamberlain University", "chamberlain.edu", "IL", 3000, 0.78, "Test Optional"],
  ["MCPHS University", "mcphs.edu", "MA", 3500, 0.82, "Test Optional"],
  ["Thomas Jefferson University", "jefferson.edu", "PA", 4000, 0.72, "Test Optional"],
  ["Rush University", "rushu.edu", "IL", 500, 0.38, "Test Optional"],
  ["Goldey-Beacom College", "gbc.edu", "DE", 1200, 0.82, "Test Optional"],
  ["Bryant University", "bryant.edu", "RI", 3500, 0.72, "Test Optional"],
  ["John Jay College of Criminal Justice", "jjay.cuny.edu", "NY", 13000, 0.48, "Test Optional"],
  ["Stockton University", "stockton.edu", "NJ", 8500, 0.78, "Test Optional"],
  ["University of New Haven", "newhaven.edu", "CT", 5000, 0.82, "Test Optional"],
  ["Endicott College", "endicott.edu", "MA", 3500, 0.78, "Test Optional"],
  ["Curry College", "curry.edu", "MA", 2500, 0.85, "Test Optional"],

  // ═══════════════════════════════════════════════════════════════════════════
  // ADDITIONAL REGIONAL PUBLICS & MISC (expanded to 750+)
  // ═══════════════════════════════════════════════════════════════════════════
  // More Northeast
  ["SUNY Purchase", "purchase.edu", "NY", 3500, 0.72, "Test Optional"],
  ["SUNY Buffalo State", "buffalostate.edu", "NY", 7000, 0.82, "Test Optional"],
  ["SUNY Morrisville", "morrisville.edu", "NY", 2800, 0.88, "Test Optional"],
  ["Castleton University", "castleton.edu", "VT", 1800, 0.88, "Test Optional"],
  ["University of Southern Maine", "usm.maine.edu", "ME", 6500, 0.88, "Test Optional"],
  ["University of Maine Farmington", "umf.maine.edu", "ME", 1600, 0.82, "Test Optional"],
  // More Mid-Atlantic / South
  ["Coastal Georgia", "ccga.edu", "GA", 3500, 0.82, "Test Optional"],
  ["Georgia College", "gcsu.edu", "GA", 6000, 0.72, "Test Optional"],
  ["University of West Georgia", "westga.edu", "GA", 12000, 0.82, "Test Optional"],
  ["Clayton State University", "clayton.edu", "GA", 6000, 0.85, "Test Optional"],
  ["University of Montevallo", "montevallo.edu", "AL", 2500, 0.72, "Test Optional"],
  ["University of West Alabama", "uwa.edu", "AL", 3500, 0.82, "Test Optional"],
  ["University of North Alabama", "una.edu", "AL", 6500, 0.78, "Test Optional"],
  ["Delta State University", "deltastate.edu", "MS", 2500, 0.88, "Test Optional"],
  ["Mississippi University for Women", "muw.edu", "MS", 2500, 0.82, "Test Optional"],
  ["Arkansas Tech University", "atu.edu", "AR", 9000, 0.85, "Test Optional"],
  ["Henderson State University", "hsu.edu", "AR", 3500, 0.82, "Test Optional"],
  ["University of Arkansas at Little Rock", "ualr.edu", "AR", 8000, 0.82, "Test Optional"],
  ["Southern Arkansas University", "saumag.edu", "AR", 3500, 0.82, "Test Optional"],
  // More Midwest
  ["University of Wisconsin Green Bay", "uwgb.edu", "WI", 7000, 0.88, "Test Optional"],
  ["University of Wisconsin Stevens Point", "uwsp.edu", "WI", 8000, 0.88, "Test Optional"],
  ["University of Wisconsin Platteville", "uwplatt.edu", "WI", 6000, 0.88, "Test Optional"],
  ["University of Wisconsin River Falls", "uwrf.edu", "WI", 5000, 0.88, "Test Optional"],
  ["University of Wisconsin Superior", "uwsuper.edu", "WI", 2500, 0.88, "Test Optional"],
  ["University of Minnesota Duluth", "d.umn.edu", "MN", 10000, 0.78, "Test Optional"],
  ["Minnesota State University Moorhead", "mnstate.edu", "MN", 5000, 0.82, "Test Optional"],
  ["St. Cloud State University", "stcloudstate.edu", "MN", 12000, 0.82, "Test Optional"],
  ["Winona State University", "winona.edu", "MN", 6500, 0.82, "Test Optional"],
  ["University of Southern Indiana", "usi.edu", "IN", 8000, 0.88, "Test Optional"],
  ["Missouri Western State University", "missouriwestern.edu", "MO", 4000, 0.88, "Test Optional"],
  ["Missouri Southern State University", "mssu.edu", "MO", 5000, 0.85, "Test Optional"],
  ["Washburn University", "washburn.edu", "KS", 5500, 0.88, "Test Optional"],
  // More West
  ["CSU Monterey Bay", "csumb.edu", "CA", 7000, 0.82, "Test Optional"],
  ["CSU Chico", "csuchico.edu", "CA", 15000, 0.85, "Test Optional"],
  ["CSU Los Angeles", "calstatela.edu", "CA", 27000, 0.62, "Test Optional"],
  ["CSU San Marcos", "csusm.edu", "CA", 14000, 0.82, "Test Optional"],
  ["Southern Utah University", "suu.edu", "UT", 12000, 0.82, "Test Optional"],
  ["Weber State University", "weber.edu", "UT", 28000, 0.88, "Test Optional"],
  ["Dixie State University", "dixie.edu", "UT", 10000, 0.88, "Test Optional"],
  ["Idaho State University", "isu.edu", "ID", 10000, 0.88, "Test Optional"],
  ["Western Colorado University", "western.edu", "CO", 2800, 0.88, "Test Optional"],
  ["Colorado Mesa University", "coloradomesa.edu", "CO", 9000, 0.88, "Test Optional"],
  ["University of Alaska Anchorage", "uaa.edu", "AK", 8000, 0.78, "Test Optional"],
  // More Texas / Oklahoma
  ["Tarleton State University", "tarleton.edu", "TX", 14000, 0.78, "Test Optional"],
  ["Angelo State University", "angelo.edu", "TX", 9000, 0.82, "Test Optional"],
  ["Texas A&M University Commerce", "tamuc.edu", "TX", 8000, 0.52, "Test Optional"],
  ["Texas A&M University Corpus Christi", "tamucc.edu", "TX", 10000, 0.82, "Test Optional"],
  ["Texas A&M University Kingsville", "tamuk.edu", "TX", 7000, 0.85, "Test Optional"],
  ["Southeastern Oklahoma State University", "se.edu", "OK", 4000, 0.88, "Test Optional"],
  ["Northeastern State University", "nsuok.edu", "OK", 7000, 0.88, "Test Optional"],
  ["Northwestern Oklahoma State University", "nwosu.edu", "OK", 2000, 0.88, "Test Optional"],
  ["East Central University", "ecok.edu", "OK", 3500, 0.82, "Test Optional"],
  ["Southwestern Oklahoma State University", "swosu.edu", "OK", 4500, 0.85, "Test Optional"],
  ["Cameron University", "cameron.edu", "OK", 3500, 0.88, "Test Optional"],
  ["Nicholls State University", "nicholls.edu", "LA", 6000, 0.82, "Test Optional"],
  ["Northwestern State University", "nsula.edu", "LA", 6000, 0.82, "Test Optional"],

  // ═══════════════════════════════════════════════════════════════════════════
  // CANADIAN UNIVERSITIES
  // ═══════════════════════════════════════════════════════════════════════════

  // ── Ontario ─────────────────────────────────────────────────────────────
  ["University of Toronto", "utoronto.ca", "ON", 73000, 0.43, "Test Optional"],
  ["University of Waterloo", "uwaterloo.ca", "ON", 40000, 0.52, "Test Optional"],
  ["Queen's University", "queensu.ca", "ON", 26000, 0.42, "Test Optional"],
  ["Western University", "uwo.ca", "ON", 33000, 0.50, "Test Optional"],
  ["McMaster University", "mcmaster.ca", "ON", 33000, 0.48, "Test Optional"],
  ["University of Ottawa", "uottawa.ca", "ON", 42000, 0.55, "Test Optional"],
  ["Carleton University", "carleton.ca", "ON", 31000, 0.68, "Test Optional"],
  ["York University", "yorku.ca", "ON", 53000, 0.65, "Test Optional"],
  ["Toronto Metropolitan University", "torontomu.ca", "ON", 38000, 0.68, "Test Optional"],
  ["University of Guelph", "uoguelph.ca", "ON", 30000, 0.58, "Test Optional"],
  ["University of Windsor", "uwindsor.ca", "ON", 15000, 0.72, "Test Optional"],
  ["Brock University", "brocku.ca", "ON", 19000, 0.72, "Test Optional"],
  ["Wilfrid Laurier University", "wlu.ca", "ON", 19000, 0.62, "Test Optional"],
  ["Trent University", "trentu.ca", "ON", 10000, 0.78, "Test Optional"],
  ["Lakehead University", "lakeheadu.ca", "ON", 8000, 0.82, "Test Optional"],
  ["Ontario Tech University", "ontariotechu.ca", "ON", 10000, 0.78, "Test Optional"],
  ["Nipissing University", "nipissingu.ca", "ON", 5000, 0.82, "Test Optional"],
  ["Laurentian University", "laurentian.ca", "ON", 6000, 0.82, "Test Optional"],

  // ── Quebec ──────────────────────────────────────────────────────────────
  ["McGill University", "mcgill.ca", "QC", 40000, 0.38, "Test Optional"],
  ["Concordia University", "concordia.ca", "QC", 46000, 0.62, "Test Optional"],
  ["Université Laval", "ulaval.ca", "QC", 43000, 0.65, "Test Optional"],
  ["Université de Montréal", "umontreal.ca", "QC", 45000, 0.55, "Test Optional"],
  ["Université du Québec à Montréal", "uqam.ca", "QC", 40000, 0.72, "Test Optional"],
  ["Université de Sherbrooke", "usherbrooke.ca", "QC", 31000, 0.62, "Test Optional"],
  ["Bishop's University", "ubishops.ca", "QC", 2600, 0.72, "Test Optional"],
  ["École de technologie supérieure", "etsmtl.ca", "QC", 11000, 0.55, "Test Optional"],

  // ── British Columbia ────────────────────────────────────────────────────
  ["University of British Columbia", "ubc.ca", "BC", 55000, 0.46, "Test Optional"],
  ["Simon Fraser University", "sfu.ca", "BC", 30000, 0.55, "Test Optional"],
  ["University of Victoria", "uvic.ca", "BC", 22000, 0.62, "Test Optional"],
  ["University of Northern British Columbia", "unbc.ca", "BC", 3500, 0.78, "Test Optional"],
  ["Royal Roads University", "royalroads.ca", "BC", 3000, 0.82, "Test Optional"],
  ["Kwantlen Polytechnic University", "kpu.ca", "BC", 13000, 0.82, "Test Optional"],
  ["Thompson Rivers University", "tru.ca", "BC", 10000, 0.82, "Test Optional"],

  // ── Alberta ─────────────────────────────────────────────────────────────
  ["University of Alberta", "ualberta.ca", "AB", 40000, 0.48, "Test Optional"],
  ["University of Calgary", "ucalgary.ca", "AB", 33000, 0.52, "Test Optional"],
  ["University of Lethbridge", "ulethbridge.ca", "AB", 8500, 0.72, "Test Optional"],
  ["MacEwan University", "macewan.ca", "AB", 13000, 0.78, "Test Optional"],
  ["Mount Royal University", "mtroyal.ca", "AB", 11000, 0.78, "Test Optional"],

  // ── Prairies ────────────────────────────────────────────────────────────
  ["University of Manitoba", "umanitoba.ca", "MB", 30000, 0.62, "Test Optional"],
  ["University of Saskatchewan", "usask.ca", "SK", 26000, 0.65, "Test Optional"],
  ["University of Regina", "uregina.ca", "SK", 15000, 0.78, "Test Optional"],
  ["University of Winnipeg", "uwinnipeg.ca", "MB", 9000, 0.82, "Test Optional"],

  // ── Atlantic ────────────────────────────────────────────────────────────
  ["Dalhousie University", "dal.ca", "NS", 19000, 0.55, "Test Optional"],
  ["Memorial University of Newfoundland", "mun.ca", "NL", 18000, 0.72, "Test Optional"],
  ["University of New Brunswick", "unb.ca", "NB", 10000, 0.72, "Test Optional"],
  ["Saint Mary's University", "smu.ca", "NS", 7000, 0.72, "Test Optional"],
  ["Acadia University", "acadiau.ca", "NS", 3500, 0.72, "Test Optional"],
  ["St. Francis Xavier University", "stfx.ca", "NS", 4500, 0.68, "Test Optional"],
  ["Cape Breton University", "cbu.ca", "NS", 5000, 0.82, "Test Optional"],
];

// NCAA Division classifications: DI, DII, DIII, or omitted = "None"
// Schools not listed default to "None" (NAIA, club-only, or no varsity athletics)
const NCAA_DIVISIONS: Record<string, string> = {
  // ── DIII Schools ──────────────────────────────────────────────────────────
  // NESCAC
  "Amherst College": "DIII",
  "Bates College": "DIII",
  "Bowdoin College": "DIII",
  "Colby College": "DIII",
  "Williams College": "DIII",
  "Middlebury College": "DIII",
  "Hamilton College": "DIII",
  "Tufts University": "DIII",
  "Connecticut College": "DIII",
  "Trinity College": "DIII",
  // Centennial Conference
  "Swarthmore College": "DIII",
  "Haverford College": "DIII",
  "Bryn Mawr College": "DIII",
  "Dickinson College": "DIII",
  "Gettysburg College": "DIII",
  "Muhlenberg College": "DIII",
  "Ursinus College": "DIII",
  "Washington College": "DIII",
  "McDaniel College": "DIII",
  "Franklin & Marshall College": "DIII",
  "Johns Hopkins University": "DIII",
  // ODAC & Virginia DIII
  "Randolph-Macon College": "DIII",
  "Roanoke College": "DIII",
  "Hampden-Sydney College": "DIII",
  "Hollins University": "DIII",
  "Sweet Briar College": "DIII",
  "Bridgewater College": "DIII",
  "Washington and Lee University": "DIII",
  "Virginia Wesleyan University": "DIII",
  "Guilford College": "DIII",
  "Randolph College": "DIII",
  "University of Lynchburg": "DIII",
  // SAA (Southern Athletic Association)
  "Sewanee University of the South": "DIII",
  "University of the South": "DIII",
  "Centre College": "DIII",
  "Hendrix College": "DIII",
  "Millsaps College": "DIII",
  "Austin College": "DIII",
  "Oglethorpe University": "DIII",
  "Birmingham-Southern College": "DIII",
  "Berry College": "DIII",
  "Rhodes College": "DIII",
  "Trinity University": "DIII",
  "Colorado College": "DIII",
  "Southwestern University": "DIII",
  // NCAC
  "Allegheny College": "DIII",
  "Denison University": "DIII",
  "Kenyon College": "DIII",
  "Oberlin College": "DIII",
  "Wooster College": "DIII",
  "College of Wooster": "DIII",
  "DePauw University": "DIII",
  "Wabash College": "DIII",
  "Wittenberg University": "DIII",
  "Ohio Wesleyan University": "DIII",
  // MIAC
  "Carleton College": "DIII",
  "Macalester College": "DIII",
  "St. Olaf College": "DIII",
  "Gustavus Adolphus College": "DIII",
  "College of Saint Benedict": "DIII",
  "Concordia College": "DIII",
  // Midwest Conference
  "Grinnell College": "DIII",
  "Lake Forest College": "DIII",
  "Knox College": "DIII",
  "Beloit College": "DIII",
  "Cornell College": "DIII",
  "Ripon College": "DIII",
  "Lawrence University": "DIII",
  // MIAA
  "Kalamazoo College": "DIII",
  "Alma College": "DIII",
  "Albion College": "DIII",
  "Hope College": "DIII",
  "Adrian College": "DIII",
  // SCIAC
  "Pomona College": "DIII",
  "Claremont McKenna College": "DIII",
  "Harvey Mudd College": "DIII",
  "Pitzer College": "DIII",
  "Occidental College": "DIII",
  "Scripps College": "DIII",
  "University of Redlands": "DIII",
  "Chapman University": "DIII",
  // NWC (Northwest Conference)
  "Whitman College": "DIII",
  "Lewis & Clark College": "DIII",
  "Willamette University": "DIII",
  "University of Puget Sound": "DIII",
  "Linfield University": "DIII",
  "Pacific University": "DIII",
  "Pacific Lutheran University": "DIII",
  "Whitworth University": "DIII",
  // Liberty League
  "Vassar College": "DIII",
  "Skidmore College": "DIII",
  "St. Lawrence University": "DIII",
  "Union College": "DIII",
  "Hobart and William Smith": "DIII",
  "Rensselaer Polytechnic Institute": "DIII",
  "Clarkson University": "DIII",
  "Rochester Institute of Technology": "DIII",
  // UAA
  "Carnegie Mellon University": "DIII",
  "Emory University": "DIII",
  "Washington University in St. Louis": "DIII",
  "New York University": "DIII",
  "University of Rochester": "DIII",
  "Brandeis University": "DIII",
  "Case Western Reserve University": "DIII",
  // CCIW
  "Wheaton College Illinois": "DIII",
  "Augustana College": "DIII",
  "Illinois Wesleyan University": "DIII",
  "North Central College": "DIII",
  // ARC
  "Luther College": "DIII",
  "Nebraska Wesleyan University": "DIII",
  // NEWMAC & NE DIII
  "MIT": "DIII",
  "University of Chicago": "DIII",
  "California Institute of Technology": "DIII",
  "Wellesley College": "DIII",
  "Smith College": "DIII",
  "Mount Holyoke College": "DIII",
  "Babson College": "DIII",
  "Clark University": "DIII",
  "Worcester Polytechnic Institute": "DIII",
  "Emerson College": "DIII",
  "Wheaton College Massachusetts": "DIII",
  "Suffolk University": "DIII",
  "Sarah Lawrence College": "DIII",
  "Wentworth Institute of Technology": "DIII",
  // Other DIII
  "Ithaca College": "DIII",
  "Susquehanna University": "DIII",
  "Elizabethtown College": "DIII",
  "York College of Pennsylvania": "DIII",
  "Christopher Newport University": "DIII",
  "Hanover College": "DIII",
  "Agnes Scott College": "DIII",
  "Transylvania University": "DIII",
  "Earlham College": "DIII",
  "Lycoming College": "DIII",
  "Juniata College": "DIII",
  "Goucher College": "DIII",
  "Salve Regina University": "DIII",
  "Roger Williams University": "DIII",
  "Moravian University": "DIII",
  "Stevens Institute of Technology": "DIII",
  "Rose-Hulman Institute of Technology": "DIII",
  "John Carroll University": "DIII",
  "Capital University": "DIII",
  "Otterbein University": "DIII",
  "Baldwin Wallace University": "DIII",
  "University of Mary Washington": "DIII",
  "University of Dallas": "DIII",
  "Centenary College of Louisiana": "DIII",
  "Mary Baldwin University": "DIII",
  "Maryville College": "DIII",
  "Franklin College": "DIII",
  "Fisk University": "DIII",
  "University of California Santa Cruz": "DIII",
  "SUNY Geneseo": "DIII",
  "SUNY New Paltz": "DIII",
  "SUNY Cortland": "DIII",
  "SUNY Oswego": "DIII",
  "University of Scranton": "DIII",
  "Rowan University": "DIII",

  // ── DII Schools ───────────────────────────────────────────────────────────
  "Hillsdale College": "DII",
  "Eckerd College": "DII",
  "Flagler College": "DII",
  "Rollins College": "DII",
  "University of Tampa": "DII",
  "Pace University": "DII",
  "Bentley University": "DII",
  "Assumption University": "DII",
  "Saint Michael's College": "DII",
  "Saint Anselm College": "DII",
  "Converse University": "DII",
  "Lees-McRae College": "DII",
  "Coker University": "DII",
  "Catawba College": "DII",
  "Claflin University": "DII",
  "Morehouse College": "DII",
  "Clark Atlanta University": "DII",
  "Tuskegee University": "DII",
  "Lincoln University": "DII",
  "Bowie State University": "DII",
  "Anderson University": "DII",
  "Harding University": "DII",
  "Spring Hill College": "DII",
  "Truman State University": "DII",
  "Rockhurst University": "DII",
  "St. Edward's University": "DII",
  "Ouachita Baptist University": "DII",
  "Mississippi College": "DII",
  "Seattle Pacific University": "DII",
  "Regis University": "DII",
  "Augustana University": "DII",
  "Sonoma State University": "DII",
  "University of Alaska Fairbanks": "DII",
  "Cal Poly Pomona": "DII",
  "San Francisco State University": "DII",
  "Texas Woman's University": "DII",
  "Wayne State University": "DII",

  // ── DI Schools ────────────────────────────────────────────────────────────
  // Ivy League
  "Harvard University": "DI",
  "Yale University": "DI",
  "Princeton University": "DI",
  "Columbia University": "DI",
  "Cornell University": "DI",
  "Brown University": "DI",
  "Dartmouth College": "DI",
  "University of Pennsylvania": "DI",
  // Patriot League
  "Colgate University": "DI",
  "Bucknell University": "DI",
  "Lafayette College": "DI",
  "College of the Holy Cross": "DI",
  "Lehigh University": "DI",
  "American University": "DI",
  "Boston University": "DI",
  "Loyola University Maryland": "DI",
  // ACC
  "Duke University": "DI",
  "University of Virginia": "DI",
  "Virginia Tech": "DI",
  "Wake Forest University": "DI",
  "Boston College": "DI",
  "Georgia Institute of Technology": "DI",
  "University of North Carolina at Chapel Hill": "DI",
  "NC State University": "DI",
  "Clemson University": "DI",
  "Florida State University": "DI",
  "University of Louisville": "DI",
  "University of Pittsburgh": "DI",
  "Syracuse University": "DI",
  "Stanford University": "DI",
  "SMU": "DI",
  "University of California Berkeley": "DI",
  // SEC
  "Vanderbilt University": "DI",
  "University of Texas at Austin": "DI",
  "Texas A&M University": "DI",
  "University of Florida": "DI",
  "University of Georgia": "DI",
  "University of Alabama": "DI",
  "Auburn University": "DI",
  "Louisiana State University": "DI",
  "University of Tennessee": "DI",
  "University of Kentucky": "DI",
  "University of South Carolina": "DI",
  "University of Mississippi": "DI",
  "University of Arkansas": "DI",
  "University of Missouri": "DI",
  "University of Oklahoma": "DI",
  // Big Ten
  "Ohio State University": "DI",
  "University of Michigan": "DI",
  "Michigan State University": "DI",
  "Penn State University": "DI",
  "University of Wisconsin Madison": "DI",
  "University of Illinois Urbana-Champaign": "DI",
  "Purdue University": "DI",
  "Indiana University Bloomington": "DI",
  "University of Minnesota": "DI",
  "University of Iowa": "DI",
  "Northwestern University": "DI",
  "Rutgers University": "DI",
  "University of Maryland College Park": "DI",
  "University of Nebraska Lincoln": "DI",
  "University of Oregon": "DI",
  "University of Southern California": "DI",
  "University of Washington": "DI",
  "University of California Los Angeles": "DI",
  // Big 12
  "Baylor University": "DI",
  "TCU": "DI",
  "Texas Tech University": "DI",
  "University of Houston": "DI",
  "University of Kansas": "DI",
  "Kansas State University": "DI",
  "Iowa State University": "DI",
  "West Virginia University": "DI",
  "University of Central Florida": "DI",
  "University of Cincinnati": "DI",
  "University of Colorado Boulder": "DI",
  "Arizona State University": "DI",
  "University of Arizona": "DI",
  "University of Utah": "DI",
  "Oklahoma State University": "DI",
  // Big East
  "Georgetown University": "DI",
  "Villanova University": "DI",
  "Seton Hall University": "DI",
  "Providence College": "DI",
  "Marquette University": "DI",
  "Butler University": "DI",
  "Creighton University": "DI",
  "Xavier University": "DI",
  "DePaul University": "DI",
  "St. John's University": "DI",
  "University of Connecticut": "DI",
  // WCC
  "Gonzaga University": "DI",
  "Santa Clara University": "DI",
  "Pepperdine University": "DI",
  "Loyola Marymount University": "DI",
  "University of San Diego": "DI",
  "University of Portland": "DI",
  "University of San Francisco": "DI",
  "Saint Mary's College of California": "DI",
  "University of the Pacific": "DI",
  // A10
  "University of Richmond": "DI",
  "University of Dayton": "DI",
  "Fordham University": "DI",
  "George Washington University": "DI",
  "George Mason University": "DI",
  "Virginia Commonwealth University": "DI",
  "St. Bonaventure University": "DI",
  "La Salle University": "DI",
  "Saint Joseph's University": "DI",
  "Duquesne University": "DI",
  "Loyola University Chicago": "DI",
  // MAAC
  "Siena College": "DI",
  "Quinnipiac University": "DI",
  "Marist College": "DI",
  "Fairfield University": "DI",
  "Canisius University": "DI",
  "Manhattan College": "DI",
  "Niagara University": "DI",
  "Rider University": "DI",
  "Iona University": "DI",
  // CAA & Northeast DI
  "Northeastern University": "DI",
  "College of William & Mary": "DI",
  "Drexel University": "DI",
  "Hofstra University": "DI",
  "Towson University": "DI",
  "College of Charleston": "DI",
  "Elon University": "DI",
  "Stony Brook University": "DI",
  "University of Delaware": "DI",
  "Monmouth University": "DI",
  "Howard University": "DI",
  "Hampton University": "DI",
  "North Carolina A&T State University": "DI",
  "Campbell University": "DI",
  "UNC Wilmington": "DI",
  // NEC
  "Wagner College": "DI",
  "Sacred Heart University": "DI",
  "Stonehill College": "DI",
  "Le Moyne University": "DI",
  // America East
  "University at Buffalo": "DI",
  "Binghamton University": "DI",
  "University of New Hampshire": "DI",
  "University of Vermont": "DI",
  "University at Albany SUNY": "DI",
  "NJIT": "DI",
  // SoCon
  "Davidson College": "DI",
  "Wofford College": "DI",
  "Furman University": "DI",
  "Samford University": "DI",
  "Mercer University": "DI",
  "UNC Greensboro": "DI",
  "Western Carolina University": "DI",
  // ASUN / Big South
  "Stetson University": "DI",
  "Jacksonville University": "DI",
  "Lipscomb University": "DI",
  "Bellarmine University": "DI",
  "Belmont University": "DI",
  "Radford University": "DI",
  "UNC Asheville": "DI",
  "High Point University": "DI",
  "Winthrop University": "DI",
  "Longwood University": "DI",
  "Presbyterian College": "DI",
  "Eastern Kentucky University": "DI",
  "University of Alabama Huntsville": "DI",
  "Florida Gulf Coast University": "DI",
  "University of North Florida": "DI",
  // Sun Belt
  "Appalachian State University": "DI",
  "James Madison University": "DI",
  "Old Dominion University": "DI",
  "Coastal Carolina University": "DI",
  "Georgia State University": "DI",
  "University of South Alabama": "DI",
  "Troy University": "DI",
  "Texas State University": "DI",
  // AAC
  "Tulane University": "DI",
  "Rice University": "DI",
  "Temple University": "DI",
  "University of South Florida": "DI",
  "University of Alabama at Birmingham": "DI",
  "Wichita State University": "DI",
  "East Carolina University": "DI",
  "UNC Charlotte": "DI",
  "University of Memphis": "DI",
  "University of North Texas": "DI",
  "University of Texas San Antonio": "DI",
  "Florida Atlantic University": "DI",
  // MVC (Missouri Valley)
  "Drake University": "DI",
  "Bradley University": "DI",
  "Valparaiso University": "DI",
  "University of Evansville": "DI",
  "Murray State University": "DI",
  "University of Northern Iowa": "DI",
  "Missouri State University": "DI",
  "Southern Illinois University Carbondale": "DI",
  "Illinois State University": "DI",
  "Saint Louis University": "DI",
  "University of Saint Thomas": "DI",
  // Horizon League
  "Northern Kentucky University": "DI",
  "Youngstown State University": "DI",
  "Wright State University": "DI",
  "Cleveland State University": "DI",
  "University of Wisconsin Milwaukee": "DI",
  // MAC
  "Miami University Ohio": "DI",
  "University of Toledo": "DI",
  "Bowling Green State University": "DI",
  "Kent State University": "DI",
  "University of Akron": "DI",
  "Western Michigan University": "DI",
  "Central Michigan University": "DI",
  "Eastern Michigan University": "DI",
  "Ball State University": "DI",
  "Northern Illinois University": "DI",
  // Summit / Big Sky / MWC / Other DI
  "University of Denver": "DI",
  "Seattle University": "DI",
  "University of Tulsa": "DI",
  "Abilene Christian University": "DI",
  "University of Massachusetts Amherst": "DI",
  "University of North Dakota": "DI",
  "University of South Dakota": "DI",
  "North Dakota State University": "DI",
  "South Dakota State University": "DI",
  "Portland State University": "DI",
  "Montana State University": "DI",
  "University of Montana": "DI",
  "Northern Arizona University": "DI",
  "University of Northern Colorado": "DI",
  "University of Wyoming": "DI",
  "University of Idaho": "DI",
  "Boise State University": "DI",
  "University of Nevada Reno": "DI",
  "University of Nevada Las Vegas": "DI",
  "University of New Mexico": "DI",
  "University of Hawaii Manoa": "DI",
  "San Diego State University": "DI",
  "Colorado State University": "DI",
  "Utah State University": "DI",
  "Oregon State University": "DI",
  "Washington State University": "DI",
  "University of California Santa Barbara": "DI",
  "University of California San Diego": "DI",
  "University of California Davis": "DI",
  "University of California Irvine": "DI",
  "San Jose State University": "DI",
  "Cal Poly San Luis Obispo": "DI",
  "Cal State Long Beach": "DI",
  "Cal State Fullerton": "DI",
  "Cal State Northridge": "DI",
  "Cal State Sacramento": "DI",
  "Fresno State": "DI",
  "University of Miami": "DI",
  // CUSA
  "Kennesaw State University": "DI",
  "Middle Tennessee State University": "DI",
  "Western Kentucky University": "DI",
  "Sam Houston State University": "DI",
  "Florida International University": "DI",
  // OVC / WAC
  "Stephen F. Austin State University": "DI",
  "Lamar University": "DI",
  "Tennessee State University": "DI",
  // SWAC (HBCU DI)
  "Florida A&M University": "DI",
  "Prairie View A&M University": "DI",
  "Southern University": "DI",
  "Grambling State University": "DI",
  "Alabama A&M University": "DI",
  "Alabama State University": "DI",
  "Jackson State University": "DI",
  "Alcorn State University": "DI",
  "Bethune-Cookman University": "DI",
  // MEAC (HBCU DI)
  "Norfolk State University": "DI",
  "Delaware State University": "DI",
  "Coppin State University": "DI",
  "South Carolina State University": "DI",
  "Morgan State University": "DI",
  // Remaining DI
  "University of Notre Dame": "DI",
  "Georgia Southern University": "DI",
  "Barnard College": "DI",

  // ── New DI Schools ──────────────────────────────────────────────────────
  // Art & Specialty
  "Savannah College of Art and Design": "DI",
  // CUNY
  "CUNY Hunter College": "DI",
  "CUNY Baruch College": "DI",
  "CUNY City College": "DI",
  "John Jay College of Criminal Justice": "DI",
  // New HBCUs — MEAC/CIAA DI
  "Winston-Salem State University": "DI",
  "North Carolina Central University": "DI",
  "Virginia State University": "DI",
  "Elizabeth City State University": "DI",
  "Savannah State University": "DI",
  // Mid-Atlantic Regional Publics
  "Salisbury University": "DI",
  // South Regional Publics
  "Jacksonville State University": "DI",
  "Austin Peay State University": "DI",
  "Tennessee Technological University": "DI",
  "East Tennessee State University": "DI",
  "Morehead State University": "DI",
  "Valdosta State University": "DI",
  // Midwest Regional Publics
  "Minnesota State University Mankato": "DI",
  "UW La Crosse": "DI",
  "UW Eau Claire": "DI",
  "UW Oshkosh": "DI",
  "UW Whitewater": "DI",
  "UW Stout": "DI",
  "Indiana State University": "DI",
  "Southeast Missouri State University": "DI",
  // West Regional Publics
  "Central Washington University": "DI",
  "Eastern Washington University": "DI",
  "Western Washington University": "DI",
  "Cal Poly Humboldt": "DI",
  "CSU Bakersfield": "DI",
  "CSU San Bernardino": "DI",
  "New Mexico State University": "DI",
  "Colorado School of Mines": "DI",
  "Stockton University": "DI",

  // ── New DII Schools ─────────────────────────────────────────────────────
  // HBCUs
  "Kentucky State University": "DII",
  "Central State University": "DII",
  "Virginia Union University": "DII",
  "Fort Valley State University": "DII",
  "Voorhees University": "DII",
  "Paine College": "DII",
  "Lane College": "DII",
  // Regional Publics
  "Shippensburg University": "DII",
  "Millersville University": "DII",
  "Kutztown University": "DII",
  "Slippery Rock University": "DII",
  "Clarion University / PennWest Clarion": "DII",
  "Edinboro University / PennWest Edinboro": "DII",
  "Frostburg State University": "DII",
  "Shepherd University": "DII",
  "Francis Marion University": "DII",
  "Lander University": "DII",
  "Columbus State University": "DII",
  "Emporia State University": "DII",
  "Pittsburg State University": "DII",
  "Fort Hays State University": "DII",
  "Minot State University": "DII",
  "Bemidji State University": "DII",
  "Grand Valley State University": "DII",
  "Ferris State University": "DII",
  "Saginaw Valley State University": "DII",
  "Lake Superior State University": "DII",
  "Northwest Missouri State University": "DII",
  "Southern Oregon University": "DII",
  "Western Oregon University": "DII",
  "Adams State University": "DII",
  "Fort Lewis College": "DII",
  "New Mexico Highlands University": "DII",
  "CSU Dominguez Hills": "DII",
  "CSU East Bay": "DII",
  "CSU Stanislaus": "DII",
  // Women's / Other
  "Simmons University": "DII",
  "Meredith College": "DII",
  "Salem College": "DII",
  "Harris-Stowe State University": "DII",

  // ── New DIII Schools ────────────────────────────────────────────────────
  "Rhode Island School of Design": "DIII",
  "Pratt Institute": "DIII",
  "Massachusetts College of Art and Design": "DIII",
  "Cooper Union": "DIII",
  "Bard College": "DIII",
  "Gordon College": "DIII",
  "Calvin University": "DIII",
  "George Fox University": "DIII",
  "Covenant College": "DIII",
  "Franciscan University of Steubenville": "DIII",
  "Olin College of Engineering": "DIII",
  "Milwaukee School of Engineering": "DIII",
  "Kettering University": "DIII",
  "Bennett College": "DIII",
  "Wilberforce University": "DIII",
  "Alverno College": "DIII",
  "Cedar Crest College": "DIII",
  "Bay Path University": "DIII",
  "Stephens College": "DIII",
  "Cottey College": "DIII",
  "Endicott College": "DIII",
  "Curry College": "DIII",
  "Bryant University": "DI",
  "University of New Haven": "DII",
  "Goldey-Beacom College": "DII",
  "Keene State College": "DIII",
  "Plymouth State University": "DIII",
  "SUNY Plattsburgh": "DIII",
  "SUNY Fredonia": "DIII",
  "SUNY Brockport": "DIII",
  "SUNY Oneonta": "DIII",
  "SUNY Potsdam": "DIII",
  "Bridgewater State University": "DIII",
  "Fitchburg State University": "DIII",
  "Framingham State University": "DIII",
  "Salem State University": "DIII",
  "Westfield State University": "DIII",
  "Worcester State University": "DIII",
  "Rhode Island College": "DIII",
  "Western Connecticut State University": "DIII",
  "Southern Connecticut State University": "DII",
  "Central Connecticut State University": "DI",
  "Eastern Connecticut State University": "DIII",
  "Wayne State College": "DII",
  "Eastern Oregon University": "DIII",
  "Thomas Jefferson University": "DII",

  // ── Additional New Schools ──────────────────────────────────────────────
  "SUNY Purchase": "DIII",
  "SUNY Buffalo State": "DIII",
  "SUNY Morrisville": "DIII",
  "Castleton University": "DIII",
  "University of Southern Maine": "DIII",
  "University of Maine Farmington": "DIII",
  "Georgia College": "DII",
  "University of West Georgia": "DII",
  "Clayton State University": "DII",
  "University of Montevallo": "DII",
  "University of West Alabama": "DII",
  "University of North Alabama": "DI",
  "Delta State University": "DII",
  "Mississippi University for Women": "DIII",
  "Arkansas Tech University": "DII",
  "Henderson State University": "DII",
  "University of Arkansas at Little Rock": "DI",
  "Southern Arkansas University": "DII",
  "University of Wisconsin Green Bay": "DI",
  "University of Wisconsin Stevens Point": "DIII",
  "University of Wisconsin Platteville": "DIII",
  "University of Wisconsin River Falls": "DIII",
  "University of Wisconsin Superior": "DIII",
  "University of Minnesota Duluth": "DII",
  "Minnesota State University Moorhead": "DII",
  "St. Cloud State University": "DII",
  "Winona State University": "DII",
  "University of Southern Indiana": "DI",
  "Missouri Western State University": "DII",
  "Missouri Southern State University": "DII",
  "Washburn University": "DII",
  "CSU Monterey Bay": "DII",
  "CSU Chico": "DII",
  "CSU Los Angeles": "DII",
  "CSU San Marcos": "DII",
  "Southern Utah University": "DI",
  "Weber State University": "DI",
  "Dixie State University": "DI",
  "Idaho State University": "DI",
  "Western Colorado University": "DII",
  "Colorado Mesa University": "DII",
  "University of Alaska Anchorage": "DII",
  "Tarleton State University": "DI",
  "Angelo State University": "DII",
  "Texas A&M University Commerce": "DI",
  "Texas A&M University Corpus Christi": "DI",
  "Texas A&M University Kingsville": "DII",
  "Southeastern Oklahoma State University": "DII",
  "Northeastern State University": "DII",
  "Northwestern Oklahoma State University": "DII",
  "East Central University": "DII",
  "Southwestern Oklahoma State University": "DII",
  "Cameron University": "DII",
  "Nicholls State University": "DI",
  "Northwestern State University": "DI",
};

export const SCHOOLS_DATABASE: SchoolRecord[] = RAW.map(([name, url, state, enrollment, admitRate, testPolicy]) => ({
  name,
  url: url.startsWith("https://") ? url : `https://www.${url}`,
  state,
  region: getRegion(state),
  campusSize: getCampusSize(enrollment),
  enrollment,
  admitRate,
  testPolicy,
  ncaaDivision: NCAA_DIVISIONS[name] || "None",
}));
